# Generated by Django 5.0.6 on 2026-06-17 20:09

import django.db.models.deletion
import storage.utils
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='KnowledgeDocument',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('file_path', models.CharField(blank=True, default='', help_text='Local path (e.g. knowledge_docs/public/FQNM.pdf) or s3://bucket/key.', max_length=1024)),
                ('uploaded_file', models.FileField(blank=True, null=True, upload_to=storage.utils.knowledge_doc_upload_path)),
                ('namespace', models.CharField(db_index=True, help_text='Pinecone namespace, e.g. alpha-compute / alpha-core / proofs.', max_length=120)),
                ('disclosure_level', models.CharField(choices=[('public', 'Public'), ('controlled_public', 'Controlled public'), ('nda_only', 'NDA only'), ('internal_only', 'Internal only'), ('prohibited', 'Prohibited')], default='public', max_length=20)),
                ('ingestion_status', models.CharField(choices=[('PENDING', 'Pending'), ('PROCESSING', 'Processing'), ('COMPLETE', 'Complete'), ('FAILED', 'Failed')], db_index=True, default='PENDING', max_length=12)),
                ('ingestion_error', models.TextField(blank=True, default='')),
                ('content_hash', models.CharField(blank=True, default='', max_length=64)),
                ('chunk_count', models.PositiveIntegerField(default=0)),
                ('last_ingested_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Knowledge document',
                'verbose_name_plural': 'Knowledge documents',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['namespace', 'ingestion_status'], name='knowledge_c_namespa_6bbf3e_idx')],
            },
        ),
        migrations.CreateModel(
            name='KnowledgeChunk',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('namespace', models.CharField(db_index=True, max_length=120)),
                ('disclosure_level', models.CharField(choices=[('public', 'Public'), ('controlled_public', 'Controlled public'), ('nda_only', 'NDA only'), ('internal_only', 'Internal only'), ('prohibited', 'Prohibited')], default='public', max_length=20)),
                ('chunk_index', models.PositiveIntegerField(default=0)),
                ('heading', models.CharField(blank=True, default='', max_length=512)),
                ('text', models.TextField()),
                ('token_estimate', models.PositiveIntegerField(default=0)),
                ('vector_id', models.CharField(blank=True, db_index=True, default='', max_length=128)),
                ('embedded', models.BooleanField(default=False)),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chunks', to='knowledge_core.knowledgedocument')),
            ],
            options={
                'verbose_name': 'Knowledge chunk',
                'verbose_name_plural': 'Knowledge chunks',
                'ordering': ['document', 'chunk_index'],
            },
        ),
        migrations.CreateModel(
            name='ClaimRecord',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('text', models.TextField()),
                ('disclosure_level', models.CharField(choices=[('public', 'Public'), ('controlled_public', 'Controlled public'), ('nda_only', 'NDA only'), ('internal_only', 'Internal only'), ('prohibited', 'Prohibited')], default='public', max_length=20)),
                ('public_reference', models.CharField(blank=True, default='', max_length=512)),
                ('is_prohibited', models.BooleanField(default=False)),
                ('document', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='claims', to='knowledge_core.knowledgedocument')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
