# Generated by Django 5.2.17 on 2026-09-04 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('knowledge_core', '0004_entity_evidence_metadata'),
    ]

    operations = [
        migrations.AlterField(
            model_name='knowledgedocument',
            name='technology_family',
            field=models.CharField(choices=[('general', 'General / cross-cutting'), ('axiom', 'AXIOM'), ('cre', 'CRE'), ('fqnm', 'FQNM'), ('alpha_compute', 'ALPHA Compute'), ('alpha_core', 'ALPHA Core'), ('cross_cutting', 'Boundary-aware / cross-cutting'), ('astop', 'ASTOP'), ('prism', 'PRISM'), ('axiom_tensor', 'AXIOM-TENSOR'), ('qnta', 'QNTA')], db_index=True, default='general', max_length=20),
        ),
    ]
