# Generated by Django 5.x — source-governance metadata only.
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [("knowledge_core", "0006_knowledge_entity_relationship_metadata")]

    operations = [
        migrations.AddField(
            model_name="knowledgedocument",
            name="claim_domains",
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name="knowledgedocument",
            name="supersedes",
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name="knowledgedocument",
            name="superseded_by",
            field=models.CharField(blank=True, default="", max_length=255),
        ),
        migrations.AddField(
            model_name="knowledgedocument",
            name="prohibited_messages",
            field=models.JSONField(blank=True, default=list),
        ),
    ]
