# Generated by Django 5.2.17 on 2026-10-03 04:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('knowledge_core', '0007_source_domain_governance'),
    ]

    operations = [
        migrations.AlterField(
            model_name='knowledgedocument',
            name='technology_family',
            field=models.CharField(choices=[('general', 'General / cross-cutting'), ('axiom', 'AXIOM'), ('cre', 'CRE'), ('fqnm', 'FQNM'), ('alpha_compute', 'AXIOM Compute'), ('alpha_core', 'AXIOM Core'), ('cross_cutting', 'Boundary-aware / cross-cutting'), ('astop', 'ASTOP'), ('prism', 'PRISM'), ('axiom_tensor', 'AXIOM-TENSOR'), ('qnta', 'QNTA')], db_index=True, default='general', max_length=20),
        ),
    ]
