# Generated by Django 5.0.6 on 2026-06-17 20:44

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Template",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "kind",
                    models.CharField(
                        choices=[
                            ("email", "Email"),
                            ("follow-up", "Follow-up"),
                            ("evaluation", "Evaluation"),
                            ("poc", "PoC"),
                            ("handoff", "Handoff"),
                        ],
                        default="email",
                        max_length=16,
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("body", models.TextField(blank=True, default="")),
                ("variables", models.JSONField(blank=True, default=list)),
            ],
            options={
                "verbose_name": "Template",
                "verbose_name_plural": "Templates",
                "ordering": ["kind", "name"],
            },
        ),
    ]
