# Generated by Django 5.0.6 on 2026-07-01 20:28

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('leads', '0002_lead_gate_decision_lead_gate_decision_reason_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ApprovalRequest',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('message_id', models.CharField(blank=True, db_index=True, default='', max_length=64)),
                ('conversation_id', models.CharField(blank=True, db_index=True, default='', max_length=64)),
                ('client_id', models.CharField(blank=True, db_index=True, default='', max_length=64)),
                ('agent_key', models.CharField(blank=True, default='', max_length=64)),
                ('claim_level', models.PositiveSmallIntegerField(choices=[(1, 'L1 — conversational'), (2, 'L2 — qualitative narrative'), (3, 'L3 — draft (citation required)'), (4, 'L4 — commercial / competitive'), (5, 'L5 — legal / binding (draft only)')], default=3)),
                ('draft_body', models.TextField(blank=True, default='')),
                ('final_body', models.TextField(blank=True, default='')),
                ('cited_chunk_ids', models.JSONField(blank=True, default=list)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('edited', 'Approved with edits'), ('rejected', 'Rejected'), ('awaiting_second', 'Awaiting second approver')], db_index=True, default='pending', max_length=20)),
                ('reason', models.TextField(blank=True, default='')),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('first_approver', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='first_approvals', to=settings.AUTH_USER_MODEL)),
                ('lead', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approval_requests', to='leads.lead')),
                ('second_approver', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='second_approvals', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Approval request',
                'verbose_name_plural': 'Approval requests',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['status', 'created_at'], name='governance__status_60c523_idx'), models.Index(fields=['claim_level', 'status'], name='governance__claim_l_6f29c6_idx')],
            },
        ),
        migrations.CreateModel(
            name='ClaimCard',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('key', models.SlugField(max_length=120, unique=True)),
                ('title', models.CharField(max_length=200)),
                ('approved_wording', models.TextField(help_text='The exact wording an agent may use for this claim.')),
                ('claim_level', models.PositiveSmallIntegerField(choices=[(1, 'L1 — conversational'), (2, 'L2 — qualitative narrative'), (3, 'L3 — draft (citation required)'), (4, 'L4 — commercial / competitive'), (5, 'L5 — legal / binding (draft only)')], default=2)),
                ('claim_record_id', models.CharField(blank=True, db_index=True, default='', max_length=64)),
                ('is_active', models.BooleanField(default=True)),
                ('notes', models.TextField(blank=True, default='')),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='owned_claim_cards', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Claim card',
                'verbose_name_plural': 'Claim cards',
                'ordering': ['claim_level', 'key'],
                'indexes': [models.Index(fields=['claim_level', 'is_active'], name='governance__claim_l_284373_idx')],
            },
        ),
    ]
