# Generated by Django 5.2.15 on 2026-07-21 06:03

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('governance', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='StreamGuardHit',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('kind', models.CharField(choices=[('halt', 'Stream halted'), ('envelope_downgrade', 'Envelope downgrade (did not stream)'), ('settle_replacement', 'Replaced at settle')], db_index=True, default='halt', max_length=24)),
                ('thread_id', models.CharField(blank=True, db_index=True, default='', max_length=64)),
                ('message_id', models.CharField(blank=True, db_index=True, default='', max_length=64)),
                ('agent_key', models.CharField(blank=True, db_index=True, default='', max_length=64)),
                ('plane', models.CharField(blank=True, default='', max_length=16)),
                ('journey_state', models.CharField(blank=True, default='', max_length=20)),
                ('pattern', models.CharField(blank=True, default='', max_length=200)),
                ('category', models.CharField(blank=True, db_index=True, default='', max_length=40)),
                ('matched_text', models.CharField(blank=True, default='', max_length=200)),
                ('position', models.PositiveIntegerField(default=0)),
                ('discarded_chars', models.PositiveIntegerField(default=0)),
                ('meta', models.JSONField(blank=True, default=dict)),
            ],
            options={
                'verbose_name': 'Stream guard hit',
                'verbose_name_plural': 'Stream guard hits',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['kind', '-created_at'], name='governance__kind_9a9ab8_idx'), models.Index(fields=['category', '-created_at'], name='governance__categor_516485_idx')],
            },
        ),
    ]
