"""
Artifact generation, versioning and delivery (Backend v6.0 §3.3).

    An artifact is generated by a NAMED AGENT RUN, GOVERNED EXACTLY LIKE A MESSAGE, and
    stored with its disclosure_level and governance_status.

── THE STRUCTURAL SAFETY DECISIONS ──────────────────────────────────────────
Two artifact builders below deliberately CANNOT express something:

1. ``boundary_waste_map`` has NO NUMERIC FIELDS. Not "numbers are discouraged" — the
   payload has nowhere to put one. A performance claim before a PoC is therefore
   structurally impossible rather than merely against policy.

2. ``poc_evidence`` KPI outcomes are pass / partial / negative / pending, and nothing
   else. There is no "promising", no "trending positive", no percentage complete.
   Playbook §State 8 is unambiguous about why:

       A negative or partial result is reported as a negative or partial result. It is
       never re-described after the fact as a partial success, a learning, or a promising
       signal. THE CREDIBILITY OF EVERY FUTURE CLAIM DEPENDS ON THIS ONE.

── DELIVERY DOES NOT NAVIGATE ───────────────────────────────────────────────
``deliver()`` appends a reference to the thread and emits ``artifact.ready``. It never
returns a redirect and never sets a route. A frontend that responds to an artifact by
navigating is a defect (§11.9).
"""

from __future__ import annotations

import logging

from django.db import transaction

from apps.journey.constants import (
    ARTIFACT_BOUNDARY_WASTE_MAP,
    ARTIFACT_DOCUMENT,
    ARTIFACT_EXECUTIVE_BRIEF,
    ARTIFACT_INTEGRATION_READINESS,
    ARTIFACT_PRODUCT_BRIEF,
    ARTIFACT_PITCH_ROOM,
    ARTIFACT_POC_EVIDENCE,
    ARTIFACT_TECHNICAL_BRIEF,
    ARTIFACT_REFLECTION,
    ARTIFACT_REVIEW_SUMMARY,
    ARTIFACT_SUCCESS_OVERVIEW,
    ARTIFACT_TYPES,
    ARTIFACTS_BY_STATE,
)
from apps.journey.models import journey_number
from apps.journey.models_artifacts import Artifact

logger = logging.getLogger("itrix")

# The only KPI outcomes that exist. Adding a fifth would be how "partial" becomes
# "promising" — so the list is closed and a test asserts it.
KPI_OUTCOMES = ("pass", "partial", "negative", "pending")


class ArtifactNotAuthorized(Exception):
    """Raised when a state does not authorize this artifact type."""


def authorized_types(journey_state: int) -> tuple[str, ...]:
    return ARTIFACTS_BY_STATE.get(journey_state or 1, ())


def is_authorized(artifact_type: str, journey_state: int) -> bool:
    return artifact_type in authorized_types(journey_state)


@transaction.atomic
def generate(thread, artifact_type: str, *, payload: dict | None = None,
             disclosure_level: str = "public", agent_run_id: str = "",
             force: bool = False) -> Artifact:
    """
    Generate and deliver an artifact into ``thread``.

    Refuses a type the subject's state does not authorize. That check is here, not in the
    view, because artifacts are generated from several places (the stop rule, a reveal, a
    regeneration task) and each of them would otherwise need to remember.
    """
    if artifact_type not in ARTIFACT_TYPES:
        raise ValueError(f"Unknown artifact type {artifact_type!r}")

    state = _state_for(thread)
    if not force and not is_authorized(artifact_type, state):
        raise ArtifactNotAuthorized(
            f"State {state} does not authorize a {artifact_type} artifact."
        )

    champion_types = {ARTIFACT_EXECUTIVE_BRIEF, ARTIFACT_TECHNICAL_BRIEF, ARTIFACT_PRODUCT_BRIEF}
    if not force and artifact_type in champion_types:
        # Internal-champion material is a Customer/Strategic Customer deliverable, not a
        # Visitor personalization device.  The same backend mirror gate that controls
        # strategic recommendations controls these artifacts, so a renderer cannot bypass
        # confirmation by asking for a brief directly.
        from apps.conversations.services import engagement_state

        if not engagement_state.recommendation_allowed(thread):
            raise ArtifactNotAuthorized(
                f"{artifact_type} requires Customer/Strategic Customer state and a confirmed or skipped mirror."
            )

    body = payload if payload is not None else build_payload(thread, artifact_type)
    governed_body, status = _govern(body, artifact_type)

    previous = (
        Artifact.objects.filter(thread=thread, type=artifact_type, superseded_by__isnull=True)
        .order_by("-version")
        .first()
    )
    version = (previous.version + 1) if previous else 1

    artifact = Artifact.objects.create(
        thread=thread,
        type=artifact_type,
        version=version,
        payload=governed_body,
        disclosure_level=disclosure_level,
        governance_status=status,
        generated_by_run=str(agent_run_id or ""),
        pinned=(artifact_type == ARTIFACT_SUCCESS_OVERVIEW),
    )

    if previous is not None:
        # SUPERSEDE, never overwrite — the earlier version is what the customer read.
        previous.superseded_by = artifact
        previous.save(update_fields=["superseded_by", "updated_at"])

    logger.info("artifact.generate %s v%s on thread=%s", artifact_type, version, thread.id)
    deliver(artifact)
    return artifact


def _state_for(thread) -> int:
    lead = getattr(thread, "lead", None)
    if lead is not None:
        return journey_number(getattr(lead, "journey_state", None)) or 1
    # Anonymous Customer threads legitimately occupy ARRIVED/IN_REVIEW/DIAGNOSED before
    # a Lead exists. Artifact authorization must follow that durable thread state or the
    # canonical DIAGNOSED reflection can never be delivered before identity capture.
    try:
        from apps.conversations.services.thread_state import current_state_number

        return current_state_number(thread)
    except Exception:  # noqa: BLE001
        return 1


def _govern(payload: dict, artifact_type: str) -> tuple[dict, str]:
    """
    Run the governance pass over the artifact's text.

    An artifact is outbound content like any other (§Phase 2: the claim checker "governs
    artifacts and generated questions, not only messages"). Held artifacts keep their
    payload server-side; the serializer withholds it.
    """
    from apps.journey.models_artifacts import Artifact as _A

    text = _collect_text(payload)
    if not text:
        return payload, _A.GovernanceStatus.AUTO_APPROVED

    try:
        from apps.governance.services.claim_checker import check

        decision = check(text, claim_level=2, context="public")
        if decision.status == "auto_approved":
            return payload, _A.GovernanceStatus.AUTO_APPROVED
        if decision.status == "blocked":
            return payload, _A.GovernanceStatus.BLOCKED
        return payload, _A.GovernanceStatus.PENDING
    except Exception:  # noqa: BLE001
        logger.exception("artifact governance unavailable; holding")
        return payload, _A.GovernanceStatus.PENDING


def _collect_text(payload) -> str:
    """Flatten a payload's strings so governance sees everything the visitor would."""
    parts: list[str] = []

    def walk(node):
        if isinstance(node, str):
            parts.append(node)
        elif isinstance(node, dict):
            for value in node.values():
                walk(value)
        elif isinstance(node, (list, tuple)):
            for item in node:
                walk(item)

    walk(payload)
    return "\n".join(parts)


def deliver(artifact) -> None:
    """
    Append the artifact to its thread and emit ``artifact.ready``.

    Best-effort fan-out: the artifact is already persisted, so a socket failure delays
    its appearance rather than losing it.
    """
    try:
        from apps.conversations.services.fan_out import broadcast_artifact_ready

        broadcast_artifact_ready(artifact)
    except Exception:  # noqa: BLE001
        logger.debug("artifact.ready emit skipped (realtime unavailable)")


def bind_capability_token(artifact) -> str:
    """
    Mint a token bound to THIS ARTIFACT.

    Grants reach to the artifact's read endpoint ONLY — never the ability to post a turn
    to the thread that produced it (§3.3). That distinction is what makes an emailed
    brief safe to forward.
    """
    from apps.journey.services import capability_token as ct

    lead = getattr(artifact.thread, "lead", None)
    subject = str(getattr(lead, "id", "") or artifact.thread_id)
    token = ct.mint(sub=subject, typ=ct.TOKEN_CLIENT_PAGE, state=f"artifact:{artifact.id}")
    artifact.capability_token = token
    artifact.save(update_fields=["capability_token", "updated_at"])
    return token


# ─────────────────────────────────────────────────────────────────────────────
# Payload builders
# ─────────────────────────────────────────────────────────────────────────────
def build_payload(thread, artifact_type: str) -> dict:
    builders = {
        ARTIFACT_REFLECTION: _reflection,
        ARTIFACT_PITCH_ROOM: _pitch_room,
        ARTIFACT_REVIEW_SUMMARY: _review_summary,
        ARTIFACT_BOUNDARY_WASTE_MAP: _boundary_waste_map,
        ARTIFACT_POC_EVIDENCE: _poc_evidence,
        ARTIFACT_INTEGRATION_READINESS: _integration_readiness,
        ARTIFACT_SUCCESS_OVERVIEW: _success_overview,
        ARTIFACT_EXECUTIVE_BRIEF: _executive_brief,
        ARTIFACT_TECHNICAL_BRIEF: _technical_brief,
        ARTIFACT_PRODUCT_BRIEF: _product_brief,
        ARTIFACT_DOCUMENT: lambda _t: {"title": "Document", "items": []},
    }
    return builders.get(artifact_type, lambda _t: {})(thread)


def _visitor_words(thread, limit: int = 40) -> list[str]:
    from apps.conversations.models import Message

    qs = Message.objects.filter(
        thread=thread, sender_kind__in=["visitor", "client"]
    ).order_by("seq", "created_at")
    rows = list(qs)
    if limit:
        rows = rows[-limit:]
    return [(m.body or "").strip() for m in rows if (m.body or "").strip()]


def _sentences(lines: list[str]) -> list[str]:
    import re

    out: list[str] = []
    for line in lines:
        for part in re.split(r"(?<=[.!?])\s+|\n+", line):
            clean = " ".join(part.split()).strip()
            if clean and len(clean) >= 4:
                out.append(clean)
    return out


def _pick(sentences: list[str], pattern: str) -> str:
    import re

    rx = re.compile(pattern, re.I)
    for sentence in reversed(sentences):
        if rx.search(sentence):
            return sentence
    return ""


def _public_safe_user_facts(lines: list[str]) -> list[str]:
    """Recent user facts, excluding control/identity turns and likely sensitive detail."""
    import re
    from apps.conversations.services import confidentiality

    controls = re.compile(
        r"^\s*(?:yes|no|proceed|this reflects my situation|refine this|start again|skip|confirmed|not now)\s*[.!]?$",
        re.I,
    )
    email = re.compile(r"\b[^\s@]+@[^\s@]+\.[^\s@]+\b")
    out: list[str] = []
    for line in lines:
        if controls.match(line) or email.search(line):
            continue
        try:
            sensitive = confidentiality.detect(line).sensitive
        except Exception:  # noqa: BLE001 - artifact source filtering must fail closed
            logger.exception("artifact confidentiality evaluation failed; withholding user text")
            continue
        if sensitive:
            continue
        clean = " ".join(line.split())
        if clean and clean not in out:
            out.append(clean)
    return out[-4:]


def _mirror_quality(thread, payload: dict, *, explicit_decision: bool, facts: list[str]) -> dict:
    """STR-03 v2.2 8x0-2 gate. Internal only; never included in artifact payload."""
    sensitive = bool(getattr(thread, "_confidential_intercept", None))
    scores = {
        "faithfulness": 2 if facts else 0,
        "decision_accuracy": 2 if explicit_decision else (1 if payload.get("affectedDecision") else 0),
        "uncertainty_discipline": 2 if str(payload.get("boundedHypothesis", "")).lower().startswith("hypothesis") and payload.get("unknowns") else 0,
        "authority_realism": 2,
        "correction_path": 2 if len(payload.get("controls") or []) == 3 else 0,
        "disclosure_safety": 0 if sensitive else 2,
        "route_restraint": 2 if not payload.get("recommendedRoute") else 0,
        "continuity_value": 2 if len(facts) >= 2 or explicit_decision else 1,
    }
    total = sum(scores.values())
    essentials = ("faithfulness", "uncertainty_discipline", "disclosure_safety", "correction_path")
    passed = total >= 12 and all(scores[k] > 0 for k in essentials)
    return {"total": total, "scores": scores, "passed": passed}


def _record_mirror_quality(thread, quality: dict) -> None:
    try:
        state = dict(getattr(thread, "conversation_commitments", None) or {})
        state["mirror_quality"] = {
            "total": int(quality.get("total") or 0),
            "passed": bool(quality.get("passed")),
            "scores": quality.get("scores") or {},
        }
        thread.conversation_commitments = state
        thread.save(update_fields=["conversation_commitments", "updated_at"])
    except Exception:  # noqa: BLE001
        logger.debug("mirror quality could not be recorded for thread %s", getattr(thread, "id", "?"))


def _reflection(thread) -> dict:
    """Canonical STR-03 Strategic Problem Mirror, v2.2.

    The payload contains exactly the six visitor-facing parts. Quality scoring is stored
    internally on the thread and deliberately omitted from the payload (SAT-11).
    """
    import re
    from apps.conversations.services import engagement_state

    lines = _visitor_words(thread, limit=40)
    facts = _public_safe_user_facts(lines)
    sentences = _sentences(facts)

    decision_sentence = _pick(
        sentences,
        r"\b(decid|decision|choose|whether|roadmap|adopt|adoption|deploy|deployment|architecture|capacity|commit|replace|substitut|scale|rollout)\b",
    )
    consequence_sentence = _pick(
        sentences,
        r"\b(cost|latency|slow|battery|thermal|power|energy|capacity|reliab|throughput|utili[sz]|risk|deadline|budget|memory|bandwidth)\b",
    )

    pressures = _pressures_from(facts)
    fact_text = " ".join(facts[-3:]) if facts else ""
    if decision_sentence:
        affected = decision_sentence
    else:
        affected = (
            "Not yet confirmed — the next thing to clarify is which workload, architecture, "
            "capacity, deployment or adoption decision this assessment is meant to inform."
        )
    consequence = consequence_sentence or (
        "Not yet confirmed — the consequence should be stated in the operational, economic, "
        "capacity, energy, reliability or strategic terms you actually use to judge this decision."
    )

    if any(p in pressures for p in ("Data-movement-bound runtime", "Underused accelerators")):
        hypothesis = (
            "Hypothesis — part of the burden may sit at representation, memory-movement or execution "
            "boundaries before additional capacity is assumed to be the answer. This is a possibility, not a finding."
        )
    elif any(p in pressures for p in ("Power or cooling limits", "Latency pressure", "Compute cost growth")):
        hypothesis = (
            "Hypothesis — part of the observed pressure may be reducible by examining how the selected workload "
            "is represented before execution, rather than assuming hardware shortage is the root cause. This is not a diagnosis."
        )
    else:
        hypothesis = (
            "Hypothesis — one structural representation or execution boundary may be worth examining before "
            "treating the current implementation or hardware as the only lever. This is a possibility, not a finding."
        )

    joined = " ".join(sentences).lower()
    unknowns: list[str] = []
    if not re.search(r"\b(baseline|current (?:latency|cost|power|throughput)|p95|p99|benchmark)\b", joined):
        unknowns.append("The baseline and the evidence standard against which a change would be judged.")
    if not re.search(r"\b(workload|pipeline|model|solver|operator|inference|training|simulation|agentic)\b", joined):
        unknowns.append("Which representative workload or workload family should anchor the assessment.")
    if not re.search(r"\b(cpu|gpu|npu|tpu|fpga|cloud|cluster|device|android|runtime|platform|environment|silicon)\b", joined):
        unknowns.append("The target execution environment and relevant software/hardware boundary.")
    if not re.search(r"\b(i decide|we decide|owner|sponsor|board|vp|evp|cto|architect|team decides|decision authority)\b", joined):
        unknowns.append("Who owns or sponsors the decision; no authority is assumed from title or company.")
    unknowns.append("What evidence can be shared safely at the current disclosure level.")
    unknowns = unknowns[:5]

    payload = {
        "kind": "strategic_problem_mirror",
        "title": "Strategic Problem Mirror",
        "statedFacts": fact_text,
        "affectedDecision": affected,
        "consequence": consequence,
        "boundedHypothesis": hypothesis,
        "unknowns": unknowns,
        "confirmOrCorrect": "Please confirm or correct this reading before any strategic route is recommended.",
        "controls": [
            {"action": "confirm", "label": "This reflects my situation"},
            {"action": "refine", "label": "Refine this"},
            {"action": "restart", "label": "Start again"},
        ],
    }
    quality = _mirror_quality(
        thread, payload, explicit_decision=bool(decision_sentence), facts=facts
    )
    _record_mirror_quality(thread, quality)

    if not quality["passed"]:
        # A below-gate draft is not displayed as a mirror. v2.2 requires a neutral
        # fallback or human review and treats fallback frequency as a quality signal.
        if getattr(thread, "mirror_status", "") != engagement_state.MIRROR_FALLBACK:
            thread.mirror_status = engagement_state.MIRROR_FALLBACK
            thread.save(update_fields=["mirror_status", "updated_at"])
        return {
            "kind": "mirror_fallback",
            "title": "One decision detail before we continue",
            "intro": (
                "I do not have enough confirmed, non-confidential information to show a reliable "
                "Strategic Problem Mirror yet. Choose or state the decision you want this conversation to inform."
            ),
            "decisionChoices": ["Capacity", "Architecture", "Roadmap", "Deployment", "Adoption", "Something else"],
            "controls": [
                {"action": "refine", "label": "Refine this"},
                {"action": "restart", "label": "Start again"},
            ],
        }

    if getattr(thread, "mirror_status", "") in (
        engagement_state.MIRROR_REFINE,
        engagement_state.MIRROR_RESTART,
        engagement_state.MIRROR_NOT_REQUIRED,
    ):
        thread.mirror_status = engagement_state.MIRROR_PENDING
        thread.save(update_fields=["mirror_status", "updated_at"])
    return payload


def _pressures_from(said: list[str]) -> list[str]:
    joined = " ".join(said)
    labels = {
        "cost": "Compute cost growth", "expensive": "Compute cost growth",
        "slow": "Slow turnaround", "latency": "Latency pressure",
        "energy": "Power or cooling limits", "power": "Power or cooling limits",
        "battery": "Power or cooling limits", "thermal": "Power or cooling limits",
        "memory": "Data-movement-bound runtime", "bandwidth": "Data-movement-bound runtime",
        "unstable": "Stability or accuracy drift", "drift": "Stability or accuracy drift",
        "utilization": "Underused accelerators", "utilisation": "Underused accelerators",
    }
    found: list[str] = []
    lowered = joined.lower()
    for keyword, label in labels.items():
        if keyword in lowered and label not in found:
            found.append(label)
    return found[:4]


def _pitch_room(thread) -> dict:
    """The 5-7 slide brief, resolved through the persona registry."""
    lead = getattr(thread, "lead", None)
    room = {"pitch_room_id": "PR-GENERIC-01", "title": "", "slides": []}
    if lead is not None:
        try:
            from apps.personas.services.pitch_room_resolver import resolve_for_lead

            room = resolve_for_lead(lead, ceiling="public")
        except Exception:  # noqa: BLE001
            logger.debug("persona room unavailable for the pitch artifact")
    return {
        "title": "Your personalized brief",
        "intro": "Based on what you shared, here is the version of itriX that matters to you.",
        "slides": room.get("slides", []),
        "action_label": "Open the brief",
        "share_label": "Email this brief to yourself",
        # persona_id / pitch_room_id are INTERNAL (§10.5) and are stripped by the
        # serializer before this reaches any client-plane payload.
        "_pitch_room_id": room.get("pitch_room_id"),
        "_persona_id": room.get("persona_id"),
        "_match_path": room.get("match_path"),
    }


def _review_summary(thread) -> dict:
    return {
        "title": "Where we would go next",
        "intro": (
            "Based on what you have described, here is the single most sensible next "
            "step — and why we think it is the right one for your situation rather than "
            "a standard one."
        ),
        "heard": _visitor_words(thread, limit=3),
        "recommended_pathway": "",
    }



def _champion_context(thread) -> dict:
    """Build a bounded, confidentiality-safe decision-support context.

    These artifacts are structured records, never a dump of model JSON.  User-provided
    wording is filtered by the same artifact safety boundary as the Strategic Problem
    Mirror; detector failure therefore prevents sensitive text from entering a brief.
    """
    lines = _public_safe_user_facts(_visitor_words(thread, limit=40))
    sentences = _sentences(lines)
    decision = _pick(
        sentences,
        r"\b(decid|decision|choose|whether|roadmap|adopt|deploy|architecture|capacity|commit|replace|scale|rollout)\b",
    )
    pressure = _pick(
        sentences,
        r"\b(cost|latency|battery|thermal|power|energy|capacity|reliab|throughput|utili[sz]|risk|budget|memory|bandwidth)\b",
    )
    workload = _pick(
        sentences,
        r"\b(workload|pipeline|model|solver|operator|inference|training|simulation|agent|runtime|platform)\b",
    )
    baseline = _pick(
        sentences,
        r"\b(baseline|current|p95|p99|benchmark|latency|throughput|power|energy|cost|capacity)\b",
    )
    locale = str(getattr(thread, "locale", "") or "en").lower()
    return {
        "locale": "ko" if locale.startswith("ko") else "en",
        "facts": lines[-4:],
        "decision": decision,
        "pressure": pressure,
        "workload": workload,
        "baseline": baseline,
        "pressures": _pressures_from(lines),
    }


def _executive_brief(thread) -> dict:
    c = _champion_context(thread)
    if c["locale"] == "ko":
        return {
            "kind": "executive_brief",
            "title": "경영진 브리프",
            "summary": c["facts"],
            "decision": c["decision"] or "의사결정 범위는 아직 확인이 필요합니다.",
            "customerImpact": c["pressure"] or "조직·제품 영향은 아직 검증되지 않았습니다.",
            "evidenceNeeded": ["현재 기준선", "대표 워크로드", "합의된 성공/실패 판단 기준"],
            "risks": ["아직 검증되지 않은 성능 또는 경제적 효과를 가정하지 않습니다.", "다음 단계의 동의는 별도로 확인합니다."],
            "recommendation": "확인된 문제 정의를 기준으로 필요한 증거와 다음 의사결정을 정리합니다.",
        }
    return {
        "kind": "executive_brief",
        "title": "Executive Brief",
        "summary": c["facts"],
        "decision": c["decision"] or "The decision scope still needs to be confirmed.",
        "customerImpact": c["pressure"] or "The organizational or product impact has not yet been validated.",
        "evidenceNeeded": ["Current baseline", "Representative workload", "Agreed pass/partial/negative criteria"],
        "risks": ["No unvalidated performance or economic outcome is assumed.", "Consent to any later stage is separate."],
        "recommendation": "Use the confirmed problem definition to agree the evidence needed for the next decision.",
    }


def _technical_brief(thread) -> dict:
    c = _champion_context(thread)
    if c["locale"] == "ko":
        return {
            "kind": "technical_brief",
            "title": "기술 브리프",
            "workload": c["workload"] or "대표 워크로드는 아직 확인이 필요합니다.",
            "baseline": c["baseline"] or "기준선은 아직 합의되지 않았습니다.",
            "observedPressures": c["pressures"],
            "boundedHypothesis": "가설 — 추가 컴퓨트 자원을 전제하기 전에 표현·데이터 이동·실행 경계를 검토할 가치가 있을 수 있습니다. 이는 진단이 아닙니다.",
            "kpis": ["워크로드별 지연시간/처리량", "전력·열·메모리 경계", "기존 기준선 대비 검증 가능한 결과"],
            "proofPlan": ["기준선 고정", "대표 입력과 환경 고정", "성공·부분·부정 결과 기준 사전 합의", "동일 조건에서 결과 검토"],
            "unknowns": ["적용 가능한 itriX 방법군은 기술 검토 전 확정하지 않습니다.", "ALPHA Core는 ALPHA Compute 가설이 검증되고 추가 실행 계층의 가치가 증거로 뒷받침될 때만 검토합니다."],
        }
    return {
        "kind": "technical_brief",
        "title": "Technical Brief",
        "workload": c["workload"] or "A representative workload still needs to be confirmed.",
        "baseline": c["baseline"] or "The baseline has not yet been agreed.",
        "observedPressures": c["pressures"],
        "boundedHypothesis": "Hypothesis — representation, data-movement or execution boundaries may be worth examining before assuming more compute is the answer. This is not a diagnosis.",
        "kpis": ["Workload-specific latency/throughput", "Power, thermal and memory boundaries", "Verifiable result against the frozen baseline"],
        "proofPlan": ["Freeze the baseline", "Freeze representative inputs and environment", "Pre-agree pass/partial/negative criteria", "Review results under like-for-like conditions"],
        "unknowns": ["No itriX method family is assigned before technical applicability is established.", "ALPHA Core is considered only after an ALPHA Compute hypothesis is validated and evidence supports value at a deeper execution layer."],
    }


def _product_brief(thread) -> dict:
    c = _champion_context(thread)
    if c["locale"] == "ko":
        return {
            "kind": "product_brief",
            "title": "제품 브리프",
            "productContext": c["facts"],
            "userImpact": c["pressure"] or "최종 사용자 영향은 아직 측정되지 않았습니다.",
            "tradeoffs": ["기능 확장과 지연시간/전력/열/비용 예산의 균형", "평균값뿐 아니라 지속 성능과 꼬리 지연시간 검토"],
            "evidenceNeeded": ["제품 경험 기준 KPI", "대표 사용 시나리오", "지속 동작 조건과 실패 기준"],
            "deploymentImplications": "검증 결과가 나오기 전에는 하드웨어 교체, ALPHA Core 또는 상용 전환을 전제하지 않습니다.",
            "nextDecision": c["decision"] or "어떤 제품·플랫폼 결정을 이 검토가 지원해야 하는지 확인합니다.",
        }
    return {
        "kind": "product_brief",
        "title": "Product Brief",
        "productContext": c["facts"],
        "userImpact": c["pressure"] or "End-user impact has not yet been measured.",
        "tradeoffs": ["Capability growth versus latency, energy, thermal and cost budgets", "Sustained performance and tail latency, not averages alone"],
        "evidenceNeeded": ["Product-experience KPI", "Representative usage scenario", "Sustained operating conditions and failure criteria"],
        "deploymentImplications": "Do not assume hardware replacement, ALPHA Core or commercial transfer before evidence supports it.",
        "nextDecision": c["decision"] or "Confirm which product or platform decision this review should support.",
    }

def _boundary_waste_map(thread) -> dict:
    """
    The Boundary Waste Map (State 7).

    NOTE WHAT IS ABSENT: there is no numeric field anywhere in this payload — no
    baseline, no delta, no percentage, no estimate. A performance claim before a PoC is
    structurally impossible here, not merely discouraged.

    The ten sections are qualitative descriptions of WHERE boundary cost appears. What it
    is WORTH is what the PoC exists to answer.
    """
    return {
        "title": "Your Alpha Compute Assessment",
        "intro": (
            "This holds the whole assessment: what we took in, the baseline we agreed, "
            "the Boundary Waste Map of your workload, technical feasibility, the "
            "benchmark we would design, and what we would recommend proving next."
        ),
        "standing_line": (
            "You should always know what is happening, why it matters, and who owns the "
            "next action."
        ),
        "sections": [
            {"key": key, "title": title, "observation": "", "boundary_kind": ""}
            for key, title in (
                ("intake", "What we took in"),
                ("representation", "How the workload is represented today"),
                ("algebraic_state", "Algebraic state and projected observation"),
                ("operator_structure", "Operator structure"),
                ("conservation_transfer", "Conservation and transfer structure"),
                ("memory_movement", "Memory and layout movement"),
                ("solver_path", "Solver and runtime path"),
                ("hardware_fit", "Hardware fit"),
                ("feasibility", "Technical feasibility"),
                ("recommendation", "What we would recommend proving next"),
            )
        ],
    }


def _poc_evidence(thread) -> dict:
    """
    PoC evidence (State 8).

    Outcomes are pass / partial / negative / pending. There is no fifth value, and
    ``validate_kpi_outcome`` refuses one. This is the artifact where the temptation to
    soften is strongest and where softening costs the most.
    """
    return {
        "title": "Proving it on your workload",
        "intro": (
            "Here is the baseline, the KPIs we agreed, and what counts as a pass, a "
            "partial result, or a negative result. Evidence appears here as it is "
            "produced."
        ),
        "baseline_agreed": "",
        "kpis": [],  # [{label, outcome, note}] — outcome ∈ KPI_OUTCOMES
        "language_rule": (
            "A negative or partial result is reported as a negative or partial result."
        ),
    }


def validate_kpi_outcome(outcome: str) -> str:
    """
    Refuse anything outside the four words.

    This is where "promising" gets stopped. A KPI vocabulary that accepts free text is a
    KPI vocabulary that will eventually contain "trending positive".
    """
    if outcome not in KPI_OUTCOMES:
        raise ValueError(
            f"Invalid KPI outcome {outcome!r}. A result is one of {KPI_OUTCOMES} — it is "
            f"never re-described as a partial success, a learning, or a promising signal."
        )
    return outcome


def _integration_readiness(thread) -> dict:
    return {
        "title": "Integration and commercial decisions",
        "intro": (
            "This holds integration readiness, the evidence both sides have accepted, "
            "the commercial decisions still open, the documents in flight, and the "
            "decision log."
        ),
        "readiness": [], "accepted_evidence": [], "open_decisions": [], "decision_log": [],
    }


def _success_overview(thread) -> dict:
    """
    The State 10 standing summary, PINNED to the top of the thread.

    Regenerated on material change (§17.3). Carries no commercial content: this is not an
    upsell surface, and the overview is the most-read thing on it.
    """
    client = getattr(thread, "client", None)
    payload = {
        "title": "Welcome back. Here is where things stand.",
        "outcomes": [], "deployments": [], "open_support": 0,
        "next_review": None, "team": [],
    }
    if client is None:
        return payload

    try:
        from apps.customer_success.services import outcome_tracker, success_review
        from apps.customer_success.models import RelationshipTeamMember, SupportRequest

        payload["outcomes"] = [
            {"title": o.title, "status": o.status, "statusLabel": o.get_status_display()}
            for o in outcome_tracker.for_client(client)[:10]
        ]
        payload["open_support"] = SupportRequest.objects.filter(
            client=client, resolved_at__isnull=True
        ).count()
        review = success_review.upcoming(client)
        payload["next_review"] = review.scheduled_at.isoformat() if review else None
        payload["team"] = [
            {"name": m.display_name, "role": m.get_role_display(), "helpsWith": m.helps_with}
            for m in RelationshipTeamMember.objects.filter(client=client)
        ]
    except Exception:  # noqa: BLE001
        logger.debug("success overview partially unavailable")
    return payload


def regenerate_success_overview(client) -> None:
    """Rebuild the pinned overview on material change."""
    from apps.conversations.models import Thread

    thread = (
        Thread.objects.filter(client=client).order_by("-last_activity_at").first()
    )
    if thread is None:
        return
    try:
        generate(thread, ARTIFACT_SUCCESS_OVERVIEW, disclosure_level="customer_contract",
                 force=True)
    except Exception:  # noqa: BLE001
        logger.exception("success overview regeneration failed for client %s", client.id)


def for_thread(thread, *, ceiling: str = "public"):
    """
    Current artifacts on a thread, filtered to what the ceiling authorizes.

    Superseded versions are excluded — the customer sees what is true now, with older
    versions reachable only through the audit trail.
    """
    from apps.journey.constants import CEILING_RANK

    rank = CEILING_RANK.get(ceiling, 0)
    return [
        artifact
        for artifact in Artifact.objects.filter(thread=thread, superseded_by__isnull=True)
        if CEILING_RANK.get(artifact.disclosure_level, 0) <= rank
    ]
