"""
Artifact generation, versioning and delivery (Backend v6.0 §3.3).

    An artifact is generated by a NAMED AGENT RUN, GOVERNED EXACTLY LIKE A MESSAGE, and
    stored with its disclosure_level and governance_status.

── THE STRUCTURAL SAFETY DECISIONS ──────────────────────────────────────────
Two artifact builders below deliberately CANNOT express something:

1. ``boundary_waste_map`` has NO NUMERIC FIELDS. Not "numbers are discouraged" — the
   payload has nowhere to put one. A performance claim before a PoC is therefore
   structurally impossible rather than merely against policy.

2. ``poc_evidence`` KPI outcomes are pass / partial / negative / pending, and nothing
   else. There is no "promising", no "trending positive", no percentage complete.
   Playbook §State 8 is unambiguous about why:

       A negative or partial result is reported as a negative or partial result. It is
       never re-described after the fact as a partial success, a learning, or a promising
       signal. THE CREDIBILITY OF EVERY FUTURE CLAIM DEPENDS ON THIS ONE.

── DELIVERY DOES NOT NAVIGATE ───────────────────────────────────────────────
``deliver()`` appends a reference to the thread and emits ``artifact.ready``. It never
returns a redirect and never sets a route. A frontend that responds to an artifact by
navigating is a defect (§11.9).
"""

from __future__ import annotations

import logging

from django.db import transaction

from apps.journey.constants import (
    ARTIFACT_BOUNDARY_WASTE_MAP,
    ARTIFACT_DOCUMENT,
    ARTIFACT_INTEGRATION_READINESS,
    ARTIFACT_PITCH_ROOM,
    ARTIFACT_POC_EVIDENCE,
    ARTIFACT_REFLECTION,
    ARTIFACT_REVIEW_SUMMARY,
    ARTIFACT_SUCCESS_OVERVIEW,
    ARTIFACT_TYPES,
    ARTIFACTS_BY_STATE,
)
from apps.journey.models import journey_number
from apps.journey.models_artifacts import Artifact

logger = logging.getLogger("itrix")

# The only KPI outcomes that exist. Adding a fifth would be how "partial" becomes
# "promising" — so the list is closed and a test asserts it.
KPI_OUTCOMES = ("pass", "partial", "negative", "pending")


class ArtifactNotAuthorized(Exception):
    """Raised when a state does not authorize this artifact type."""


def authorized_types(journey_state: int) -> tuple[str, ...]:
    return ARTIFACTS_BY_STATE.get(journey_state or 1, ())


def is_authorized(artifact_type: str, journey_state: int) -> bool:
    return artifact_type in authorized_types(journey_state)


@transaction.atomic
def generate(thread, artifact_type: str, *, payload: dict | None = None,
             disclosure_level: str = "public", agent_run_id: str = "",
             force: bool = False) -> Artifact:
    """
    Generate and deliver an artifact into ``thread``.

    Refuses a type the subject's state does not authorize. That check is here, not in the
    view, because artifacts are generated from several places (the stop rule, a reveal, a
    regeneration task) and each of them would otherwise need to remember.
    """
    if artifact_type not in ARTIFACT_TYPES:
        raise ValueError(f"Unknown artifact type {artifact_type!r}")

    state = _state_for(thread)
    if not force and not is_authorized(artifact_type, state):
        raise ArtifactNotAuthorized(
            f"State {state} does not authorize a {artifact_type} artifact."
        )

    body = payload if payload is not None else build_payload(thread, artifact_type)
    governed_body, status = _govern(body, artifact_type)

    previous = (
        Artifact.objects.filter(thread=thread, type=artifact_type, superseded_by__isnull=True)
        .order_by("-version")
        .first()
    )
    version = (previous.version + 1) if previous else 1

    artifact = Artifact.objects.create(
        thread=thread,
        type=artifact_type,
        version=version,
        payload=governed_body,
        disclosure_level=disclosure_level,
        governance_status=status,
        generated_by_run=str(agent_run_id or ""),
        pinned=(artifact_type == ARTIFACT_SUCCESS_OVERVIEW),
    )

    if previous is not None:
        # SUPERSEDE, never overwrite — the earlier version is what the customer read.
        previous.superseded_by = artifact
        previous.save(update_fields=["superseded_by", "updated_at"])

    logger.info("artifact.generate %s v%s on thread=%s", artifact_type, version, thread.id)
    deliver(artifact)
    return artifact


def _state_for(thread) -> int:
    lead = getattr(thread, "lead", None)
    if lead is None:
        return 1
    return journey_number(getattr(lead, "journey_state", None)) or 1


def _govern(payload: dict, artifact_type: str) -> tuple[dict, str]:
    """
    Run the governance pass over the artifact's text.

    An artifact is outbound content like any other (§Phase 2: the claim checker "governs
    artifacts and generated questions, not only messages"). Held artifacts keep their
    payload server-side; the serializer withholds it.
    """
    from apps.journey.models_artifacts import Artifact as _A

    text = _collect_text(payload)
    if not text:
        return payload, _A.GovernanceStatus.AUTO_APPROVED

    try:
        from apps.governance.services.claim_checker import check

        decision = check(text, claim_level=2, context="public")
        if decision.status == "auto_approved":
            return payload, _A.GovernanceStatus.AUTO_APPROVED
        if decision.status == "blocked":
            return payload, _A.GovernanceStatus.BLOCKED
        return payload, _A.GovernanceStatus.PENDING
    except Exception:  # noqa: BLE001
        logger.exception("artifact governance unavailable; holding")
        return payload, _A.GovernanceStatus.PENDING


def _collect_text(payload) -> str:
    """Flatten a payload's strings so governance sees everything the visitor would."""
    parts: list[str] = []

    def walk(node):
        if isinstance(node, str):
            parts.append(node)
        elif isinstance(node, dict):
            for value in node.values():
                walk(value)
        elif isinstance(node, (list, tuple)):
            for item in node:
                walk(item)

    walk(payload)
    return "\n".join(parts)


def deliver(artifact) -> None:
    """
    Append the artifact to its thread and emit ``artifact.ready``.

    Best-effort fan-out: the artifact is already persisted, so a socket failure delays
    its appearance rather than losing it.
    """
    try:
        from apps.conversations.services.fan_out import broadcast_artifact_ready

        broadcast_artifact_ready(artifact)
    except Exception:  # noqa: BLE001
        logger.debug("artifact.ready emit skipped (realtime unavailable)")


def bind_capability_token(artifact) -> str:
    """
    Mint a token bound to THIS ARTIFACT.

    Grants reach to the artifact's read endpoint ONLY — never the ability to post a turn
    to the thread that produced it (§3.3). That distinction is what makes an emailed
    brief safe to forward.
    """
    from apps.journey.services import capability_token as ct

    lead = getattr(artifact.thread, "lead", None)
    subject = str(getattr(lead, "id", "") or artifact.thread_id)
    token = ct.mint(sub=subject, typ=ct.TOKEN_CLIENT_PAGE, state=f"artifact:{artifact.id}")
    artifact.capability_token = token
    artifact.save(update_fields=["capability_token", "updated_at"])
    return token


# ─────────────────────────────────────────────────────────────────────────────
# Payload builders
# ─────────────────────────────────────────────────────────────────────────────
def build_payload(thread, artifact_type: str) -> dict:
    builders = {
        ARTIFACT_REFLECTION: _reflection,
        ARTIFACT_PITCH_ROOM: _pitch_room,
        ARTIFACT_REVIEW_SUMMARY: _review_summary,
        ARTIFACT_BOUNDARY_WASTE_MAP: _boundary_waste_map,
        ARTIFACT_POC_EVIDENCE: _poc_evidence,
        ARTIFACT_INTEGRATION_READINESS: _integration_readiness,
        ARTIFACT_SUCCESS_OVERVIEW: _success_overview,
        ARTIFACT_DOCUMENT: lambda _t: {"title": "Document", "items": []},
    }
    return builders.get(artifact_type, lambda _t: {})(thread)


def _visitor_words(thread, limit: int = 5) -> list[str]:
    from apps.conversations.models import Message

    return [
        (m.body or "").strip()
        for m in Message.objects.filter(
            thread=thread, sender_kind__in=["visitor", "client"]
        ).order_by("seq", "created_at")[:limit]
        if (m.body or "").strip()
    ]


def _reflection(thread) -> dict:
    """
    "What we think is actually happening" (Playbook State 3).

    Qualitative only. The reflection's job is to prove we LISTENED — quantifying anything
    here would be claiming a result before any evidence exists.
    """
    said = _visitor_words(thread)
    return {
        "title": "What we think is actually happening",
        "intro": (
            "Here is how we would describe your bottleneck, the layer we think it may "
            "really sit in, and the ALPHA route that would be worth examining first."
        ),
        "acknowledgement": said[0] if said else "",
        "recognized_pressures": _pressures_from(said),
        "likely_hidden_boundary": "",
        "initial_alpha_route": "ALPHA Compute assessment of one representative workload",
        "action_label": "Open the full reflection",
    }


def _pressures_from(said: list[str]) -> list[str]:
    from apps.agents.services.coverage import analyse_text

    joined = " ".join(said)
    labels = {
        "cost": "Compute cost growth", "expensive": "Compute cost growth",
        "slow": "Slow turnaround", "latency": "Latency pressure",
        "energy": "Power or cooling limits", "power": "Power or cooling limits",
        "memory": "Data-movement-bound runtime", "bandwidth": "Data-movement-bound runtime",
        "unstable": "Stability or accuracy drift", "drift": "Stability or accuracy drift",
        "utilization": "Underused accelerators", "utilisation": "Underused accelerators",
    }
    found: list[str] = []
    lowered = joined.lower()
    for keyword, label in labels.items():
        if keyword in lowered and label not in found:
            found.append(label)
    return found[:4]


def _pitch_room(thread) -> dict:
    """The 5-7 slide brief, resolved through the persona registry."""
    lead = getattr(thread, "lead", None)
    room = {"pitch_room_id": "PR-GENERIC-01", "title": "", "slides": []}
    if lead is not None:
        try:
            from apps.personas.services.pitch_room_resolver import resolve_for_lead

            room = resolve_for_lead(lead, ceiling="public")
        except Exception:  # noqa: BLE001
            logger.debug("persona room unavailable for the pitch artifact")
    return {
        "title": "Your personalized brief",
        "intro": "Based on what you shared, here is the version of itriX that matters to you.",
        "slides": room.get("slides", []),
        "action_label": "Open the brief",
        "share_label": "Email this brief to yourself",
        # persona_id / pitch_room_id are INTERNAL (§10.5) and are stripped by the
        # serializer before this reaches any client-plane payload.
        "_pitch_room_id": room.get("pitch_room_id"),
        "_persona_id": room.get("persona_id"),
        "_match_path": room.get("match_path"),
    }


def _review_summary(thread) -> dict:
    return {
        "title": "Where we would go next",
        "intro": (
            "Based on what you have described, here is the single most sensible next "
            "step — and why we think it is the right one for your situation rather than "
            "a standard one."
        ),
        "heard": _visitor_words(thread, limit=3),
        "recommended_pathway": "",
    }


def _boundary_waste_map(thread) -> dict:
    """
    The Boundary Waste Map (State 7).

    NOTE WHAT IS ABSENT: there is no numeric field anywhere in this payload — no
    baseline, no delta, no percentage, no estimate. A performance claim before a PoC is
    structurally impossible here, not merely discouraged.

    The ten sections are qualitative descriptions of WHERE boundary cost appears. What it
    is WORTH is what the PoC exists to answer.
    """
    return {
        "title": "Your Alpha Compute Assessment",
        "intro": (
            "This holds the whole assessment: what we took in, the baseline we agreed, "
            "the Boundary Waste Map of your workload, technical feasibility, the "
            "benchmark we would design, and what we would recommend proving next."
        ),
        "standing_line": (
            "You should always know what is happening, why it matters, and who owns the "
            "next action."
        ),
        "sections": [
            {"key": key, "title": title, "observation": "", "boundary_kind": ""}
            for key, title in (
                ("intake", "What we took in"),
                ("representation", "How the workload is represented today"),
                ("algebraic_state", "Algebraic state and projected observation"),
                ("operator_structure", "Operator structure"),
                ("conservation_transfer", "Conservation and transfer structure"),
                ("memory_movement", "Memory and layout movement"),
                ("solver_path", "Solver and runtime path"),
                ("hardware_fit", "Hardware fit"),
                ("feasibility", "Technical feasibility"),
                ("recommendation", "What we would recommend proving next"),
            )
        ],
    }


def _poc_evidence(thread) -> dict:
    """
    PoC evidence (State 8).

    Outcomes are pass / partial / negative / pending. There is no fifth value, and
    ``validate_kpi_outcome`` refuses one. This is the artifact where the temptation to
    soften is strongest and where softening costs the most.
    """
    return {
        "title": "Proving it on your workload",
        "intro": (
            "Here is the baseline, the KPIs we agreed, and what counts as a pass, a "
            "partial result, or a negative result. Evidence appears here as it is "
            "produced."
        ),
        "baseline_agreed": "",
        "kpis": [],  # [{label, outcome, note}] — outcome ∈ KPI_OUTCOMES
        "language_rule": (
            "A negative or partial result is reported as a negative or partial result."
        ),
    }


def validate_kpi_outcome(outcome: str) -> str:
    """
    Refuse anything outside the four words.

    This is where "promising" gets stopped. A KPI vocabulary that accepts free text is a
    KPI vocabulary that will eventually contain "trending positive".
    """
    if outcome not in KPI_OUTCOMES:
        raise ValueError(
            f"Invalid KPI outcome {outcome!r}. A result is one of {KPI_OUTCOMES} — it is "
            f"never re-described as a partial success, a learning, or a promising signal."
        )
    return outcome


def _integration_readiness(thread) -> dict:
    return {
        "title": "Integration and commercial decisions",
        "intro": (
            "This holds integration readiness, the evidence both sides have accepted, "
            "the commercial decisions still open, the documents in flight, and the "
            "decision log."
        ),
        "readiness": [], "accepted_evidence": [], "open_decisions": [], "decision_log": [],
    }


def _success_overview(thread) -> dict:
    """
    The State 10 standing summary, PINNED to the top of the thread.

    Regenerated on material change (§17.3). Carries no commercial content: this is not an
    upsell surface, and the overview is the most-read thing on it.
    """
    client = getattr(thread, "client", None)
    payload = {
        "title": "Welcome back. Here is where things stand.",
        "outcomes": [], "deployments": [], "open_support": 0,
        "next_review": None, "team": [],
    }
    if client is None:
        return payload

    try:
        from apps.customer_success.services import outcome_tracker, success_review
        from apps.customer_success.models import RelationshipTeamMember, SupportRequest

        payload["outcomes"] = [
            {"title": o.title, "status": o.status, "statusLabel": o.get_status_display()}
            for o in outcome_tracker.for_client(client)[:10]
        ]
        payload["open_support"] = SupportRequest.objects.filter(
            client=client, resolved_at__isnull=True
        ).count()
        review = success_review.upcoming(client)
        payload["next_review"] = review.scheduled_at.isoformat() if review else None
        payload["team"] = [
            {"name": m.display_name, "role": m.get_role_display(), "helpsWith": m.helps_with}
            for m in RelationshipTeamMember.objects.filter(client=client)
        ]
    except Exception:  # noqa: BLE001
        logger.debug("success overview partially unavailable")
    return payload


def regenerate_success_overview(client) -> None:
    """Rebuild the pinned overview on material change."""
    from apps.conversations.models import Thread

    thread = (
        Thread.objects.filter(client=client).order_by("-last_activity_at").first()
    )
    if thread is None:
        return
    try:
        generate(thread, ARTIFACT_SUCCESS_OVERVIEW, disclosure_level="customer_contract",
                 force=True)
    except Exception:  # noqa: BLE001
        logger.exception("success overview regeneration failed for client %s", client.id)


def for_thread(thread, *, ceiling: str = "public"):
    """
    Current artifacts on a thread, filtered to what the ceiling authorizes.

    Superseded versions are excluded — the customer sees what is true now, with older
    versions reachable only through the audit trail.
    """
    from apps.journey.constants import CEILING_RANK

    rank = CEILING_RANK.get(ceiling, 0)
    return [
        artifact
        for artifact in Artifact.objects.filter(thread=thread, superseded_by__isnull=True)
        if CEILING_RANK.get(artifact.disclosure_level, 0) <= rank
    ]
