# Generated by Django 5.0.6 on 2026-06-17 19:27

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('visitors', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReviewSession',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('client_id', models.CharField(blank=True, db_index=True, default='', max_length=128)),
                ('visitor_type', models.CharField(blank=True, default='unknown', max_length=32)),
                ('status', models.CharField(choices=[('STARTED', 'Started'), ('PROMPTED', 'Prompted'), ('QUALIFIED', 'Qualified')], db_index=True, default='STARTED', max_length=12)),
                ('prompt', models.TextField(blank=True, default='')),
                ('pressure_areas', models.JSONField(blank=True, default=list)),
                ('environment', models.CharField(blank=True, default='', max_length=64)),
                ('nda_recommended', models.BooleanField(default=False)),
                ('nda_signals', models.JSONField(blank=True, default=list)),
                ('answers', models.JSONField(blank=True, default=dict)),
                ('score_breakdown', models.JSONField(blank=True, default=dict)),
                ('score_total', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('tier', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('product_route', models.CharField(blank=True, default='', max_length=20)),
                ('license_pathway', models.CharField(blank=True, default='', max_length=20)),
                ('placeholder_lead_id', models.UUIDField(blank=True, null=True)),
                ('visitor_session', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='review_sessions', to='visitors.visitorsession')),
            ],
            options={
                'verbose_name': 'Review session',
                'verbose_name_plural': 'Review sessions',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['status', 'created_at'], name='review_revi_status_5c90e3_idx'), models.Index(fields=['tier'], name='review_revi_tier_da7971_idx')],
            },
        ),
    ]
