# Generated by Django 5.2.15 on 2026-07-21 07:10

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clients', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ReleaseNote',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('version', models.CharField(db_index=True, max_length=64)),
                ('title', models.CharField(max_length=300)),
                ('body', models.TextField(blank=True, default='')),
                ('released_at', models.DateTimeField(db_index=True)),
                ('customer_scope', models.CharField(blank=True, db_index=True, default='', max_length=64)),
                ('is_published', models.BooleanField(db_index=True, default=False)),
            ],
            options={
                'verbose_name': 'Release note',
                'verbose_name_plural': 'Release notes',
                'ordering': ['-released_at'],
            },
        ),
        migrations.CreateModel(
            name='SuccessPlan',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(default='Our shared plan', max_length=300)),
                ('summary', models.TextField(blank=True, default='')),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('starts_on', models.DateField(blank=True, null=True)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='success_plans', to='clients.client')),
            ],
            options={
                'verbose_name': 'Success plan',
                'verbose_name_plural': 'Success plans',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SuccessPlanMilestone',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('horizon', models.PositiveSmallIntegerField(choices=[(30, '30 days'), (60, '60 days'), (90, '90 days')], db_index=True, default=30)),
                ('title', models.CharField(max_length=300)),
                ('owner_side', models.CharField(choices=[('itrix', 'itriX'), ('customer', 'Customer'), ('shared', 'Shared')], default='shared', max_length=16)),
                ('owner_name', models.CharField(blank=True, default='', max_length=200)),
                ('status', models.CharField(choices=[('on_plan', 'On plan'), ('at_risk', 'At risk'), ('off_plan', 'Off plan'), ('achieved', 'Achieved')], default='on_plan', max_length=16)),
                ('needs_customer_action', models.BooleanField(default=False)),
                ('due_on', models.DateField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='milestones', to='customer_success.successplan')),
            ],
            options={
                'verbose_name': 'Success plan milestone',
                'verbose_name_plural': 'Success plan milestones',
                'ordering': ['horizon', 'due_on', 'created_at'],
            },
        ),
        migrations.CreateModel(
            name='SuccessReview',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('scheduled_at', models.DateTimeField(db_index=True)),
                ('agenda', models.JSONField(blank=True, default=list)),
                ('notes', models.TextField(blank=True, default='')),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='success_reviews', to='clients.client')),
            ],
            options={
                'verbose_name': 'Success review',
                'verbose_name_plural': 'Success reviews',
                'ordering': ['scheduled_at'],
            },
        ),
        migrations.CreateModel(
            name='ChangeLogEntry',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('kind', models.CharField(choices=[('completed', 'Work completed'), ('resolved', 'Issue resolved'), ('shipped', 'Update shipped'), ('awaiting_decision', 'Waiting on your decision')], db_index=True, max_length=24)),
                ('title', models.CharField(max_length=300)),
                ('detail', models.TextField(blank=True, default='')),
                ('occurred_at', models.DateTimeField(db_index=True)),
                ('surfaced_at', models.DateTimeField(blank=True, null=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='change_log', to='clients.client')),
            ],
            options={
                'verbose_name': 'Change log entry',
                'verbose_name_plural': 'Change log',
                'ordering': ['-occurred_at'],
                'indexes': [models.Index(fields=['client', '-occurred_at'], name='customer_su_client__9c06e7_idx')],
            },
        ),
        migrations.CreateModel(
            name='DeploymentHealth',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('environment', models.CharField(default='production', max_length=120)),
                ('status', models.CharField(choices=[('healthy', 'Healthy'), ('degraded', 'Degraded'), ('down', 'Down'), ('unknown', 'Unknown')], db_index=True, default='unknown', max_length=16)),
                ('version', models.CharField(blank=True, default='', max_length=64)),
                ('last_checked_at', models.DateTimeField(blank=True, null=True)),
                ('incident_note', models.TextField(blank=True, default='')),
                ('known_limitations', models.TextField(blank=True, default='')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deployments', to='clients.client')),
            ],
            options={
                'verbose_name': 'Deployment health',
                'verbose_name_plural': 'Deployment health',
                'ordering': ['client', 'environment'],
                'indexes': [models.Index(fields=['client', 'status'], name='customer_su_client__5d23ad_idx')],
            },
        ),
        migrations.CreateModel(
            name='FeedbackPulse',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('score', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('comment', models.TextField(blank=True, default='')),
                ('wants_follow_up', models.BooleanField(default=False)),
                ('acknowledged_at', models.DateTimeField(blank=True, null=True)),
                ('acknowledged_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='acknowledged_pulses', to=settings.AUTH_USER_MODEL)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='feedback_pulses', to='clients.client')),
            ],
            options={
                'verbose_name': 'Feedback pulse',
                'verbose_name_plural': 'Feedback pulses',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['client', '-created_at'], name='customer_su_client__b5fd54_idx')],
            },
        ),
        migrations.CreateModel(
            name='Outcome',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=300)),
                ('description', models.TextField(blank=True, default='')),
                ('status', models.CharField(choices=[('on_plan', 'On plan'), ('at_risk', 'At risk'), ('off_plan', 'Off plan'), ('achieved', 'Achieved')], db_index=True, default='on_plan', max_length=16)),
                ('measure', models.CharField(blank=True, default='', max_length=300)),
                ('owner_side', models.CharField(choices=[('itrix', 'itriX'), ('customer', 'Customer'), ('shared', 'Shared')], default='shared', max_length=16)),
                ('owner_name', models.CharField(blank=True, default='', max_length=200)),
                ('target_date', models.DateField(blank=True, null=True)),
                ('achieved_at', models.DateTimeField(blank=True, null=True)),
                ('status_note', models.TextField(blank=True, default='')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='outcomes', to='clients.client')),
            ],
            options={
                'verbose_name': 'Outcome',
                'verbose_name_plural': 'Outcomes',
                'ordering': ['target_date', '-created_at'],
                'indexes': [models.Index(fields=['client', 'status'], name='customer_su_client__2025f2_idx')],
            },
        ),
        migrations.CreateModel(
            name='RelationshipTeamMember',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('display_name', models.CharField(max_length=200)),
                ('role', models.CharField(choices=[('customer_success', 'Customer success'), ('technical', 'Technical'), ('executive', 'Executive'), ('support', 'Support')], db_index=True, max_length=24)),
                ('helps_with', models.CharField(blank=True, default='', max_length=300)),
                ('contact_email', models.EmailField(blank=True, default='', max_length=254)),
                ('is_primary', models.BooleanField(default=False)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='relationship_team', to='clients.client')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='customer_relationships', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Relationship team member',
                'verbose_name_plural': 'Relationship team',
                'ordering': ['role', '-is_primary', 'display_name'],
                'indexes': [models.Index(fields=['client', 'role'], name='customer_su_client__95e5ef_idx')],
            },
        ),
        migrations.CreateModel(
            name='SupportRequest',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('thread_id', models.CharField(blank=True, db_index=True, default='', max_length=64)),
                ('subject', models.CharField(blank=True, default='', max_length=300)),
                ('body', models.TextField(blank=True, default='')),
                ('status', models.CharField(choices=[('open', 'Open'), ('in_progress', 'In progress'), ('waiting_on_customer', 'Waiting on customer'), ('resolved', 'Resolved')], db_index=True, default='open', max_length=24)),
                ('urgency', models.CharField(choices=[('low', 'Low'), ('normal', 'Normal'), ('high', 'High'), ('critical', 'Critical')], db_index=True, default='normal', max_length=16)),
                ('blocking', models.BooleanField(db_index=True, default=False)),
                ('owner_name', models.CharField(blank=True, default='', max_length=200)),
                ('sla_due_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('first_response_at', models.DateTimeField(blank=True, null=True)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('resolution_note', models.TextField(blank=True, default='')),
                ('customer_confirmed_resolved', models.BooleanField(blank=True, null=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='support_requests', to='clients.client')),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='support_requests', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Support request',
                'verbose_name_plural': 'Support requests',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['client', 'status'], name='customer_su_client__367cde_idx'), models.Index(fields=['status', 'sla_due_at'], name='customer_su_status_c663a3_idx')],
            },
        ),
    ]
