"""
Visitor tracking models.

``VisitorSession`` is the anonymous thread that ties together everything a single
visitor does on the public site: which room(s) they entered, the review they start,
and (in Phase 2) the lead they become. The frontend generates a stable ``client_id``
in the browser and sends it on every call; we use it to recognise the same visitor
across requests without cookies.

``RoomEntry`` records each visit to one of the 10 visitor rooms (Surface 1). The
``Room`` choices mirror ``itrix-web/src/types/room.types.ts``.
"""

from __future__ import annotations

from django.db import models

from apps.core.models import BaseModel


class VisitorType(models.TextChoices):
    """Coarse visitor intent, aligned with the web personas / rooms."""

    PROBLEM_OWNER = "problem_owner", "Problem owner"
    TECHNICAL = "technical", "Technical evaluator"
    RESEARCH = "research", "Researcher / scholar"
    INVESTOR = "investor", "Investor"
    PARTNER = "partner", "Strategic partner"
    SHAREHOLDER = "shareholder", "Shareholder"
    MEDIA = "media", "Media / journalist"
    CREATOR = "creator", "Creator"
    PUBLIC_INFRASTRUCTURE = "public_infrastructure", "Public infrastructure"
    EXPLORER = "explorer", "Curious explorer"
    UNKNOWN = "unknown", "Unknown"


class Room(models.TextChoices):
    """The 10 visitor rooms on the public site."""

    BOTTLENECK = "bottleneck", "Compute Bottleneck"
    TECHNICAL = "technical", "Technical"
    RESEARCH = "research", "Research"
    INVESTOR = "investor", "Investor"
    PARTNER = "partner", "Partnership"
    SHAREHOLDER = "shareholder", "Shareholder Update"
    MEDIA = "media", "Media / Journalist"
    CREATOR = "creator", "Creator / YouTuber"
    PUBLIC_INFRASTRUCTURE = "public-infrastructure", "Public Infrastructure"
    EXPLORE = "explore", "Curious Explorer"


class VisitorSession(BaseModel):
    """One anonymous visitor thread on the public site."""

    client_id = models.CharField(
        max_length=128,
        blank=True,
        default="",
        db_index=True,
        help_text="Stable id generated by the browser; groups a visitor's requests.",
    )
    visitor_type = models.CharField(
        max_length=32,
        choices=VisitorType.choices,
        default=VisitorType.UNKNOWN,
        blank=True,
    )

    # Lightweight, privacy-conscious context (no precise PII).
    referrer = models.CharField(max_length=512, blank=True, default="")
    user_agent = models.CharField(max_length=512, blank=True, default="")
    ip_hash = models.CharField(
        max_length=64,
        blank=True,
        default="",
        help_text="Salted hash of the client IP (never the raw address).",
    )
    landing_path = models.CharField(max_length=512, blank=True, default="")

    room_entry_count = models.PositiveIntegerField(default=0)
    last_seen_at = models.DateTimeField(auto_now=True)

    class Meta:
        ordering = ["-created_at"]
        verbose_name = "Visitor session"
        verbose_name_plural = "Visitor sessions"
        indexes = [
            models.Index(fields=["client_id", "created_at"]),
        ]

    def __str__(self) -> str:
        who = self.client_id or "anon"
        return f"VisitorSession({who}, {self.visitor_type})"

    def register_room_entry(self) -> None:
        self.room_entry_count = (self.room_entry_count or 0) + 1
        self.save(update_fields=["room_entry_count", "last_seen_at", "updated_at"])


class RoomEntry(BaseModel):
    """A single visit to one of the public visitor rooms."""

    session = models.ForeignKey(
        VisitorSession,
        on_delete=models.CASCADE,
        related_name="room_entries",
    )
    room = models.CharField(max_length=40, choices=Room.choices)
    visitor_type = models.CharField(
        max_length=32,
        choices=VisitorType.choices,
        default=VisitorType.UNKNOWN,
        blank=True,
    )

    class Meta:
        ordering = ["-created_at"]
        verbose_name = "Room entry"
        verbose_name_plural = "Room entries"
        indexes = [models.Index(fields=["room", "created_at"])]

    def __str__(self) -> str:
        return f"RoomEntry({self.room})"
