# Generated by Django 5.2.15 on 2026-07-21 07:10

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('conversations', '0003_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Attachment',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('uploaded_by_kind', models.CharField(choices=[('session', 'Visitor session'), ('client', 'Client'), ('team', 'Team')], default='session', max_length=16)),
                ('uploaded_by_id', models.CharField(blank=True, db_index=True, default='', max_length=128)),
                ('filename', models.CharField(max_length=512)),
                ('declared_mime', models.CharField(blank=True, default='', max_length=200)),
                ('detected_mime', models.CharField(blank=True, default='', max_length=200)),
                ('bytes', models.BigIntegerField(default=0)),
                ('sha256', models.CharField(blank=True, db_index=True, default='', max_length=64)),
                ('blob_key', models.CharField(blank=True, default='', max_length=512)),
                ('status', models.CharField(choices=[('staged', 'Staged'), ('scanning', 'Scanning'), ('scanned', 'Scanned'), ('extracting', 'Extracting'), ('ready', 'Ready'), ('quarantined', 'Quarantined'), ('failed', 'Failed'), ('purged', 'Purged')], db_index=True, default='staged', max_length=16)),
                ('pre_nda', models.BooleanField(db_index=True, default=True)),
                ('retention_expires_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('purged_at', models.DateTimeField(blank=True, null=True)),
                ('risk_flags', models.JSONField(blank=True, default=list)),
                ('visitor_note', models.CharField(blank=True, default='', max_length=300)),
                ('thread', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='conversations.thread')),
            ],
            options={
                'verbose_name': 'Attachment',
                'verbose_name_plural': 'Attachments',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='AttachmentAuditEntry',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('action', models.CharField(db_index=True, max_length=24)),
                ('plane', models.CharField(blank=True, default='', max_length=16)),
                ('subject', models.CharField(blank=True, default='', max_length=128)),
                ('purpose', models.CharField(blank=True, default='', max_length=300)),
                ('detail', models.CharField(blank=True, default='', max_length=300)),
                ('attachment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='audit_entries', to='attachments.attachment')),
            ],
            options={
                'verbose_name': 'Attachment audit entry',
                'verbose_name_plural': 'Attachment audit entries',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='AttachmentExcerpt',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('ordinal', models.PositiveIntegerField(default=0)),
                ('text', models.TextField()),
                ('char_count', models.PositiveIntegerField(default=0)),
                ('attachment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='excerpts', to='attachments.attachment')),
            ],
            options={
                'verbose_name': 'Attachment excerpt',
                'verbose_name_plural': 'Attachment excerpts',
                'ordering': ['attachment', 'ordinal'],
            },
        ),
        migrations.CreateModel(
            name='AttachmentExtraction',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('handler', models.CharField(db_index=True, default='opaque', max_length=32)),
                ('text', models.TextField(blank=True, null=True)),
                ('page_count', models.PositiveIntegerField(default=0)),
                ('char_count', models.PositiveIntegerField(default=0)),
                ('truncated', models.BooleanField(default=False)),
                ('error', models.TextField(blank=True, default='')),
                ('duration_ms', models.PositiveIntegerField(default=0)),
                ('metadata_only', models.BooleanField(default=False)),
                ('attachment', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='extraction', to='attachments.attachment')),
            ],
            options={
                'verbose_name': 'Attachment extraction',
                'verbose_name_plural': 'Attachment extractions',
            },
        ),
        migrations.CreateModel(
            name='AttachmentScan',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('engine', models.CharField(default='builtin', max_length=64)),
                ('verdict', models.CharField(choices=[('clean', 'Clean'), ('malicious', 'Malicious'), ('suspicious', 'Suspicious'), ('error', 'Error')], db_index=True, default='error', max_length=16)),
                ('detail', models.TextField(blank=True, default='')),
                ('scanned_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('attachment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scans', to='attachments.attachment')),
            ],
            options={
                'verbose_name': 'Attachment scan',
                'verbose_name_plural': 'Attachment scans',
                'ordering': ['-scanned_at'],
            },
        ),
        migrations.AddIndex(
            model_name='attachment',
            index=models.Index(fields=['thread', 'status'], name='attachments_thread__e963b7_idx'),
        ),
        migrations.AddIndex(
            model_name='attachment',
            index=models.Index(fields=['status', 'retention_expires_at'], name='attachments_status_2bd6a3_idx'),
        ),
        migrations.AddIndex(
            model_name='attachment',
            index=models.Index(fields=['pre_nda', 'retention_expires_at'], name='attachments_pre_nda_7c336c_idx'),
        ),
        migrations.AddIndex(
            model_name='attachmentauditentry',
            index=models.Index(fields=['attachment', 'action'], name='attachments_attachm_087c87_idx'),
        ),
    ]
