# Generated by Django 5.2.15 on 2026-08-13 06:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attachments', '0001_initial'),
        ('conversations', '0004_thread_current_state_thread_questions_asked'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attachment',
            name='thread',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='conversations.thread'),
        ),
    ]
