# Generated by Django 5.0.6 on 2026-06-17 20:44

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("leads", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="NDARecord",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("lead_name", models.CharField(blank=True, default="", max_length=255)),
                ("company", models.CharField(blank=True, default="", max_length=255)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("required", "Required"),
                            ("sent", "Sent"),
                            ("signed", "Signed"),
                        ],
                        default="required",
                        max_length=12,
                    ),
                ),
                ("checklist", models.JSONField(blank=True, default=list)),
                ("requested_at", models.DateTimeField(auto_now_add=True)),
                ("sent_at", models.DateTimeField(blank=True, null=True)),
                ("signed_at", models.DateTimeField(blank=True, null=True)),
                (
                    "lead",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="nda",
                        to="leads.lead",
                    ),
                ),
            ],
            options={
                "verbose_name": "NDA record",
                "verbose_name_plural": "NDA records",
                "ordering": ["-requested_at"],
            },
        ),
    ]
