# Generated by Django 5.2.14 on 2026-06-19 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nda', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ndarecord',
            name='body',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='ndarecord',
            name='decline_reason',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='ndarecord',
            name='doc_type',
            field=models.CharField(choices=[('mutual', 'Mutual NDA'), ('one-way', 'One-way NDA')], default='mutual', max_length=12),
        ),
        migrations.AddField(
            model_name='ndarecord',
            name='signer_email',
            field=models.EmailField(blank=True, default='', max_length=254),
        ),
        migrations.AddField(
            model_name='ndarecord',
            name='signer_name',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='ndarecord',
            name='status',
            field=models.CharField(choices=[('required', 'Required'), ('sent', 'Sent'), ('signed', 'Signed'), ('declined', 'Declined'), ('expired', 'Expired')], default='required', max_length=12),
        ),
    ]
