# Generated by Django 5.0.6 on 2026-06-17 20:09

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('review', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Lead',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('client_id', models.CharField(blank=True, db_index=True, default='', max_length=128)),
                ('visitor_name', models.CharField(blank=True, default='', max_length=200)),
                ('company', models.CharField(blank=True, default='', max_length=200)),
                ('email', models.EmailField(blank=True, db_index=True, default='', max_length=254)),
                ('industry', models.CharField(blank=True, default='', max_length=120)),
                ('role', models.CharField(blank=True, default='', max_length=120)),
                ('product_route', models.CharField(choices=[('alpha_compute', 'ALPHA Compute'), ('alpha_core', 'ALPHA Core'), ('both', 'Both'), ('general', 'General')], default='general', max_length=20)),
                ('commercial_path', models.CharField(choices=[('non_exclusive', 'Non-Exclusive'), ('exclusive', 'Exclusive'), ('strategic', 'Strategic'), ('none', 'None')], default='none', max_length=20)),
                ('special_rights', models.CharField(choices=[('None', 'None'), ('Field', 'Field'), ('Territory', 'Territory'), ('Product-Category', 'Product-Category'), ('Acquisition', 'Acquisition'), ('Exclusive-Global', 'Exclusive-Global'), ('Time-Limited', 'Time-Limited')], default='None', max_length=40)),
                ('compute_bottleneck', models.TextField(blank=True, default='', help_text='AI-generated summary of the bottleneck.')),
                ('primary_pain', models.CharField(blank=True, default='', max_length=120)),
                ('workload_type', models.CharField(blank=True, default='', max_length=120)),
                ('current_stack', models.JSONField(blank=True, default=list)),
                ('commercial_intent', models.CharField(blank=True, default='', max_length=120)),
                ('timeline', models.CharField(blank=True, default='', max_length=120)),
                ('score', models.PositiveSmallIntegerField(default=0)),
                ('tier', models.PositiveSmallIntegerField(default=4)),
                ('score_breakdown', models.JSONField(blank=True, default=dict)),
                ('recommended_next_step', models.TextField(blank=True, default='')),
                ('human_handoff_trigger', models.BooleanField(default=False)),
                ('qualification', models.JSONField(blank=True, default=dict)),
                ('status', models.CharField(choices=[('New', 'New'), ('Contacted', 'Contacted'), ('Meeting Booked', 'Meeting Booked'), ('NDA', 'NDA'), ('Evaluation', 'Evaluation'), ('PoC', 'PoC'), ('Licensed', 'Licensed'), ('Closed', 'Closed'), ('Qualifying', 'Qualifying'), ('Nurture', 'Nurture'), ('Negotiation', 'Negotiation'), ('Lost', 'Lost')], db_index=True, default='New', max_length=20)),
                ('cta_clicked', models.CharField(blank=True, default='', max_length=120)),
                ('documents_viewed', models.PositiveIntegerField(default=0)),
                ('sla_response_due_at', models.DateTimeField(blank=True, null=True)),
                ('first_response_at', models.DateTimeField(blank=True, null=True)),
                ('escalated', models.BooleanField(default=False)),
                ('escalated_at', models.DateTimeField(blank=True, null=True)),
                ('submitted_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='owned_leads', to=settings.AUTH_USER_MODEL)),
                ('review_session', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='leads', to='review.reviewsession')),
            ],
            options={
                'verbose_name': 'Lead',
                'verbose_name_plural': 'Leads',
                'ordering': ['-submitted_at'],
            },
        ),
        migrations.CreateModel(
            name='LeadActivity',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('type', models.CharField(choices=[('submission', 'Submission'), ('status_change', 'Status change'), ('owner_change', 'Owner change'), ('note', 'Note'), ('email_sent', 'Email sent'), ('escalated', 'Escalated'), ('nda', 'NDA'), ('evaluation', 'Evaluation'), ('poc', 'PoC'), ('paid_eval', 'Paid evaluation')], max_length=20)),
                ('label', models.CharField(max_length=255)),
                ('by_name', models.CharField(blank=True, default='', max_length=200)),
                ('meta', models.JSONField(blank=True, default=dict)),
                ('by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lead_activities', to=settings.AUTH_USER_MODEL)),
                ('lead', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activities', to='leads.lead')),
            ],
            options={
                'verbose_name_plural': 'Lead activities',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='LeadNote',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('body', models.TextField()),
                ('author_name', models.CharField(blank=True, default='', max_length=200)),
                ('author', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lead_notes', to=settings.AUTH_USER_MODEL)),
                ('lead', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notes', to='leads.lead')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='lead',
            index=models.Index(fields=['tier', 'status'], name='leads_lead_tier_b35804_idx'),
        ),
        migrations.AddIndex(
            model_name='lead',
            index=models.Index(fields=['status', 'submitted_at'], name='leads_lead_status_bf49e6_idx'),
        ),
        migrations.AddIndex(
            model_name='lead',
            index=models.Index(fields=['owner', 'status'], name='leads_lead_owner_i_9c310b_idx'),
        ),
    ]
