# Generated by Django 5.0.6 on 2026-07-01 19:27

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0001_initial'),
        ('review', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='lead',
            name='gate_decision',
            field=models.CharField(blank=True, default='', max_length=16),
        ),
        migrations.AddField(
            model_name='lead',
            name='gate_decision_reason',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='lead',
            name='journey_state',
            field=models.CharField(db_index=True, default='ARRIVED', help_text='Progressive-disclosure state (apps.journey.JourneyState).', max_length=20),
        ),
        migrations.AddField(
            model_name='lead',
            name='value_delivered_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddIndex(
            model_name='lead',
            index=models.Index(fields=['journey_state'], name='leads_lead_journey_2aabc1_idx'),
        ),
    ]
