# Generated by Django 5.2.14 on 2026-06-19 10:37

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='leadactivity',
            name='type',
            field=models.CharField(choices=[('submission', 'Submission'), ('status_change', 'Status change'), ('owner_change', 'Owner change'), ('note', 'Note'), ('email_sent', 'Email sent'), ('escalated', 'Escalated'), ('nda', 'NDA'), ('evaluation', 'Evaluation'), ('poc', 'PoC'), ('paid_eval', 'Paid evaluation'), ('meeting', 'Meeting')], max_length=20),
        ),
        migrations.CreateModel(
            name='LeadMeeting',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('scheduled_at', models.DateTimeField()),
                ('duration_mins', models.PositiveIntegerField(default=30)),
                ('attendee', models.CharField(blank=True, default='', max_length=200)),
                ('location', models.CharField(blank=True, default='', max_length=500)),
                ('notes', models.TextField(blank=True, default='')),
                ('booked_by_name', models.CharField(blank=True, default='', max_length=200)),
                ('booked_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='booked_meetings', to=settings.AUTH_USER_MODEL)),
                ('lead', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='meetings', to='leads.lead')),
            ],
            options={
                'ordering': ['-scheduled_at'],
            },
        ),
    ]
