# Generated by Django 5.0.6 on 2026-07-07 17:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0002_alter_leadactivity_type_leadmeeting'),
        ('leads', '0002_lead_gate_decision_lead_gate_decision_reason_and_more'),
    ]

    operations = [
    ]
