# Generated by Django 5.2.15 on 2026-07-21 06:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conversations', '0002_thread_spine'),
        ('leads', '0003_merge_20260707_2009'),
        ('personas', '0001_initial'),
        ('review', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='lead',
            name='attachment_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='lead',
            name='first_thread',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='originated_leads', to='conversations.thread'),
        ),
        migrations.AddField(
            model_name='lead',
            name='journey_number',
            field=models.PositiveSmallIntegerField(blank=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name='lead',
            name='persona',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='leads', to='personas.persona'),
        ),
        migrations.AddField(
            model_name='lead',
            name='state_key',
            field=models.CharField(blank=True, db_index=True, default='', max_length=20),
        ),
        migrations.AddIndex(
            model_name='lead',
            index=models.Index(fields=['journey_number'], name='leads_lead_journey_10c9e8_idx'),
        ),
    ]
