# Backend v7.2 Phase 4 — lead provenance.
#
# `self_serve` is the new case: somebody arrived, opened a workspace, and may not have said
# anything yet. R70 keeps those out of every queue, tier count, conversion rate and SLA
# clock until a first turn lands — counting them would corrupt the exact metrics Layer 1
# exists to produce.

# Generated by Django 5.2.15 on 2026-07-30 18:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0004_thread_spine'),
    ]

    operations = [
        migrations.AddField(
            model_name='lead',
            name='lead_source',
            field=models.CharField(choices=[('conversation', 'Conversation'), ('self_serve', 'Self-serve registration'), ('imported', 'Imported')], db_index=True, default='conversation', max_length=16),
        ),
    ]
