# Generated by Django 5.2.17 on 2026-10-03 04:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0007_product_route_neutrality'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lead',
            name='current_marketing_stage',
            field=models.CharField(choices=[('discovery', 'Discovery'), ('sales_platform', 'AI-Powered Sales Platform'), ('astop', 'ASTOP'), ('alpha_compute', 'AXIOM Compute'), ('alpha_core', 'AXIOM Core')], db_index=True, default='discovery', max_length=24),
        ),
        migrations.AlterField(
            model_name='lead',
            name='product_route',
            field=models.CharField(choices=[('undetermined', 'Not yet assessed'), ('astop', 'ASTOP'), ('alpha_compute', 'AXIOM Compute'), ('alpha_core', 'AXIOM Core'), ('both', 'Multiple products (legacy)'), ('general', 'General / legacy')], default='undetermined', max_length=20),
        ),
    ]
