# Generated by Django 5.2.15 on 2026-07-21 07:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('governance', '0002_stream_guard_hit'),
    ]

    operations = [
        migrations.AddField(
            model_name='claimcard',
            name='disclosure_ceiling',
            field=models.CharField(choices=[('public', 'Public'), ('controlled_public', 'Controlled public'), ('nda_only', 'NDA only'), ('customer_contract', 'Customer contract'), ('internal_only', 'Internal only')], db_index=True, default='public', max_length=24),
        ),
    ]
