# Generated by Django 5.2.17 on 2026-10-03 04:56

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clients', '0007_client_session_version'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CommerceAudit',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('action', models.CharField(max_length=40)),
                ('subject_id', models.UUIDField()),
                ('actor_id', models.UUIDField(null=True)),
                ('detail', models.JSONField(default=dict)),
            ],
            options={
                'ordering': ['-created_at'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='License',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(default='active', max_length=16)),
                ('token_version', models.PositiveIntegerField(default=0)),
                ('revoked_at', models.DateTimeField(null=True)),
            ],
            options={
                'ordering': ['-created_at'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='LegalRelease',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('kind', models.CharField(choices=[('lo', 'License Order'), ('branch', 'Branch Agreement')], max_length=16)),
                ('version', models.CharField(max_length=40)),
                ('body', models.TextField()),
                ('sha256', models.CharField(max_length=64)),
                ('approved_at', models.DateTimeField()),
                ('active', models.BooleanField(default=False)),
                ('approved_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Branch',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(default='applied', max_length=16)),
                ('approved_at', models.DateTimeField(null=True)),
                ('agreement_body', models.TextField(blank=True)),
                ('agreement_hash', models.CharField(blank=True, max_length=64)),
                ('acceptance_session_hash', models.CharField(blank=True, max_length=64)),
                ('accepted_at', models.DateTimeField(null=True)),
                ('code', models.CharField(max_length=32, null=True, unique=True)),
                ('approved_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('client', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to='clients.client')),
                ('parent', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='commerce.branch')),
                ('agreement', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='commerce.legalrelease')),
            ],
            options={
                'ordering': ['-created_at'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Delivery',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('build_id', models.CharField(max_length=100)),
                ('platform', models.CharField(max_length=32)),
                ('artifact_sha256', models.CharField(max_length=64)),
                ('signing_identity', models.CharField(max_length=200)),
                ('license', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='commerce.license')),
            ],
            options={
                'ordering': ['-created_at'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('kind', models.CharField(max_length=16)),
                ('seats', models.PositiveIntegerField()),
                ('currency', models.CharField(default='USD', max_length=3)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('discount', models.PositiveIntegerField(default=0)),
                ('identity_snapshot', models.JSONField()),
                ('legal_body', models.TextField()),
                ('legal_hash', models.CharField(max_length=64)),
                ('accepted_at', models.DateTimeField(null=True)),
                ('acceptance_session_hash', models.CharField(blank=True, max_length=64)),
                ('status', models.CharField(default='quoted', max_length=24)),
                ('payment_reference', models.CharField(max_length=200, null=True, unique=True)),
                ('paid_at', models.DateTimeField(null=True)),
                ('lineage', models.JSONField(default=list)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='clients.client')),
                ('legal', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='commerce.legalrelease')),
                ('referral', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='orders', to='commerce.branch')),
            ],
            options={
                'ordering': ['-created_at'],
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='license',
            name='order',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to='commerce.order'),
        ),
        migrations.AddField(
            model_name='branch',
            name='qualifying_order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='branch_applications', to='commerce.order'),
        ),
        migrations.CreateModel(
            name='PaymentEvent',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('provider_id', models.CharField(max_length=200, unique=True)),
                ('payload_hash', models.CharField(max_length=64)),
                ('kind', models.CharField(max_length=24)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='commerce.order')),
            ],
            options={
                'ordering': ['-created_at'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Refund',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('reason', models.TextField()),
                ('status', models.CharField(default='requested', max_length=24)),
                ('approved_at', models.DateTimeField(null=True)),
                ('provider_reference', models.CharField(blank=True, max_length=200)),
                ('approved_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('order', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to='commerce.order')),
            ],
            options={
                'ordering': ['-created_at'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Reward',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('level', models.PositiveSmallIntegerField()),
                ('net_base', models.DecimalField(decimal_places=2, max_digits=12)),
                ('amount', models.DecimalField(decimal_places=4, max_digits=16)),
                ('eligible_at', models.DateTimeField()),
                ('status', models.CharField(default='pending', max_length=24)),
                ('payout_reference', models.CharField(blank=True, max_length=200)),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='commerce.branch')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='commerce.order')),
            ],
        ),
        migrations.CreateModel(
            name='Seat',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('email', models.EmailField(max_length=254)),
                ('active', models.BooleanField(default=True)),
                ('license', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='assignments', to='commerce.license')),
            ],
        ),
        migrations.CreateModel(
            name='Activation',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('environment_hash', models.CharField(max_length=64)),
                ('token_version', models.PositiveIntegerField()),
                ('valid_until', models.DateTimeField()),
                ('revoked_at', models.DateTimeField(null=True)),
                ('seat', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='commerce.seat')),
            ],
            options={
                'ordering': ['-created_at'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='VerifiedIdentity',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('kind', models.CharField(choices=[('individual', 'Individual'), ('organization', 'Organization')], max_length=16)),
                ('details', models.JSONField(default=dict)),
                ('verified_email', models.EmailField(max_length=254)),
                ('verified_at', models.DateTimeField()),
                ('client', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to='clients.client')),
                ('verified_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'abstract': False,
            },
        ),
        migrations.AddConstraint(
            model_name='legalrelease',
            constraint=models.UniqueConstraint(fields=('kind', 'version'), name='commerce_legal_version'),
        ),
        migrations.AddConstraint(
            model_name='reward',
            constraint=models.UniqueConstraint(fields=('order', 'level'), name='commerce_reward_level'),
        ),
        migrations.AddConstraint(
            model_name='seat',
            constraint=models.UniqueConstraint(condition=models.Q(('active', True)), fields=('license', 'email'), name='commerce_active_seat'),
        ),
    ]
