# Generated by Django 5.2.17 on 2026-10-04 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commerce', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='activation',
            name='last_validated_at',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='activation',
            name='renewal_due_at',
            field=models.DateTimeField(null=True),
        ),
    ]
