# Generated by Django 5.2.17 on 2026-10-05 03:26

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0007_client_session_version'),
        ('commerce', '0002_activation_last_validated_at_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='JourneyDecision',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('outcome', models.CharField(choices=[('continue', 'Continue'), ('tune', 'Tune'), ('another_workload', 'Try another workload'), ('expand', 'Expand'), ('stop', 'Stop'), ('refund', 'Refund')], max_length=24)),
                ('workload', models.CharField(max_length=200)),
                ('comparable', models.BooleanField(default=False)),
                ('fidelity', models.CharField(choices=[('preserved', 'Preserved'), ('failed', 'Failed'), ('unknown', 'Unknown')], max_length=16)),
                ('net_value', models.CharField(choices=[('positive', 'Positive'), ('nonpositive', 'Nonpositive'), ('unknown', 'Unknown')], max_length=16)),
                ('measured_results', models.TextField(blank=True)),
                ('qualitative_feedback', models.TextField()),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='clients.client')),
                ('license', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='commerce.license')),
            ],
            options={
                'ordering': ['-created_at'],
                'abstract': False,
            },
        ),
    ]
