# Generated by Django 5.2.17 on 2026-10-07 09:25

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0007_client_session_version'),
        ('commerce', '0003_journeydecision'),
    ]

    operations = [
        migrations.AddField(
            model_name='legalrelease',
            name='policy',
            field=models.CharField(default='legacy', max_length=24),
        ),
        migrations.AddField(
            model_name='license',
            name='auto_renew',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='license',
            name='cancelled_at',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='license',
            name='ends_at',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='license',
            name='entitlement_kind',
            field=models.CharField(default='legacy', max_length=16),
        ),
        migrations.AddField(
            model_name='license',
            name='starts_at',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='purpose',
            field=models.CharField(default='legacy', max_length=16),
        ),
        migrations.AddField(
            model_name='order',
            name='recurring_authorized_at',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='refund_days',
            field=models.PositiveSmallIntegerField(default=30),
        ),
        migrations.AlterField(
            model_name='legalrelease',
            name='kind',
            field=models.CharField(choices=[('lo', 'License Order'), ('branch', 'Branch Agreement'), ('trial', 'Trial terms')], max_length=16),
        ),
        migrations.CreateModel(
            name='RenewalRecord',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('provider_id', models.CharField(max_length=200, unique=True)),
                ('payment_reference', models.CharField(max_length=200, unique=True)),
                ('payload_hash', models.CharField(max_length=64)),
                ('period_start', models.DateTimeField()),
                ('period_end', models.DateTimeField()),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('refund_status', models.CharField(blank=True, max_length=24)),
                ('refund_reason', models.TextField(blank=True)),
                ('paid_at', models.DateTimeField()),
                ('license', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='renewals', to='commerce.license')),
            ],
            options={
                'ordering': ['-created_at'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='TrialEnrollment',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('identity_key', models.CharField(max_length=64, unique=True)),
                ('starts_at', models.DateTimeField()),
                ('ends_at', models.DateTimeField()),
                ('client', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to='clients.client')),
                ('joined_order', models.OneToOneField(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='converted_trial', to='commerce.order')),
                ('license', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to='commerce.license')),
            ],
            options={
                'ordering': ['-created_at'],
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='order',
            name='trial',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='orders', to='commerce.trialenrollment'),
        ),
    ]
