# Generated by Django 5.2.15 on 2026-07-21 07:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('review', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='reviewsession',
            name='stop_reason',
            field=models.CharField(blank=True, db_index=True, default='', max_length=40),
        ),
    ]
