# Generated by Django 5.0.6 on 2026-07-01 19:27

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('leads', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AgentRun',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('agent_key', models.CharField(db_index=True, max_length=64)),
                ('client_id', models.CharField(blank=True, db_index=True, default='', max_length=64)),
                ('status', models.CharField(choices=[('ok', 'OK'), ('fallback', 'Deterministic fallback'), ('error', 'Error')], default='ok', max_length=16)),
                ('used_ai', models.BooleanField(default=False)),
                ('governance_status', models.CharField(choices=[('auto_approved', 'Auto-approved'), ('pending', 'Pending review'), ('approved', 'Approved'), ('blocked', 'Blocked')], default='auto_approved', max_length=16)),
                ('claim_level', models.PositiveSmallIntegerField(default=0)),
                ('input_summary', models.JSONField(blank=True, default=dict)),
                ('output', models.JSONField(blank=True, default=dict)),
                ('chunk_ids', models.JSONField(blank=True, default=list)),
                ('error', models.TextField(blank=True, default='')),
                ('duration_ms', models.PositiveIntegerField(default=0)),
                ('lead', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='agent_runs', to='leads.lead')),
            ],
            options={
                'verbose_name': 'Agent run',
                'verbose_name_plural': 'Agent runs',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['agent_key', 'created_at'], name='agents_agen_agent_k_816bcd_idx'), models.Index(fields=['lead', 'agent_key'], name='agents_agen_lead_id_c78e0a_idx')],
            },
        ),
    ]
