# Generated by Django 5.0.6 on 2026-07-01 19:27

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('leads', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='JourneyTransition',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('from_state', models.CharField(choices=[('ARRIVED', 'Arrived'), ('IN_REVIEW', 'In review'), ('DIAGNOSED', 'Diagnosed'), ('CLIENT_PAGE', 'Client page'), ('INVITED', 'Invited'), ('CLIENT', 'Client'), ('ENGAGED', 'Engaged'), ('DORMANT', 'Dormant')], max_length=20)),
                ('to_state', models.CharField(choices=[('ARRIVED', 'Arrived'), ('IN_REVIEW', 'In review'), ('DIAGNOSED', 'Diagnosed'), ('CLIENT_PAGE', 'Client page'), ('INVITED', 'Invited'), ('CLIENT', 'Client'), ('ENGAGED', 'Engaged'), ('DORMANT', 'Dormant')], max_length=20)),
                ('event', models.CharField(choices=[('prompt', 'Prompt submitted'), ('qualify', 'Qualification completed'), ('reveal_client_page', 'Client page revealed'), ('gate_invite', 'Account invite gate passed'), ('gate_dormant', 'Did not pass invite gate'), ('accept_invite', 'Invite accepted (client created)'), ('engage', 'NDA / evaluation started'), ('reactivate', 'Returned with a stronger signal')], max_length=32)),
                ('reveal', models.CharField(blank=True, choices=[('client_page', 'Client page'), ('account_invite', 'Account invite'), ('portal', 'Portal'), ('data_room', 'Data room')], default='', max_length=20)),
                ('meta', models.JSONField(blank=True, default=dict)),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='journey_transitions', to=settings.AUTH_USER_MODEL)),
                ('lead', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='journey_transitions', to='leads.lead')),
            ],
            options={
                'verbose_name': 'Journey transition',
                'verbose_name_plural': 'Journey transitions',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['lead', 'to_state'], name='journey_jou_lead_id_251885_idx'), models.Index(fields=['to_state', 'created_at'], name='journey_jou_to_stat_98b49b_idx')],
            },
        ),
    ]
