# Generated by Django 5.2.15 on 2026-07-21 06:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('journey', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='journeytransition',
            name='event',
            field=models.CharField(choices=[('prompt', 'Prompt submitted'), ('qualify', 'Qualification completed'), ('reveal_client_page', 'Client page revealed'), ('gate_invite', 'Account invite gate passed'), ('gate_dormant', 'Did not pass invite gate'), ('accept_invite', 'Invite accepted (client created)'), ('engage', 'NDA / evaluation started'), ('reactivate', 'Returned with a stronger signal'), ('first_turn', 'First turn posted on an empty thread'), ('loop_closed', 'Question loop closed for the qualification band'), ('nda_signed', 'NDA signed'), ('first_payment', 'First payment recorded'), ('poc_start', 'PoC started'), ('integration_start', 'Integration started'), ('contract_executed', 'Contract executed')], max_length=32),
        ),
        migrations.AlterField(
            model_name='journeytransition',
            name='from_state',
            field=models.CharField(choices=[('ARRIVED', 'Arrived'), ('IN_REVIEW', 'In review'), ('DIAGNOSED', 'Diagnosed'), ('CLIENT_PAGE', 'Client page'), ('INVITED', 'Invited'), ('NDA_REVIEW', 'NDA review'), ('ASSESSMENT', 'Assessment'), ('POC', 'PoC'), ('INTEGRATION', 'Integration'), ('CUSTOMER_SUCCESS', 'Customer success'), ('DORMANT', 'Dormant'), ('CLIENT', 'Client (deprecated — use NDA_REVIEW)'), ('ENGAGED', 'Engaged (deprecated — use ASSESSMENT/POC/INTEGRATION)')], max_length=20),
        ),
        migrations.AlterField(
            model_name='journeytransition',
            name='reveal',
            field=models.CharField(blank=True, choices=[('client_page', '1 Client page'), ('account_invite', '2 Account creation'), ('portal', '3 Client portal'), ('data_room', '4 NDA data room'), ('success_overlay', '5 Success overlay'), ('customer_success_home', '6 Customer-success home')], default='', max_length=24),
        ),
        migrations.AlterField(
            model_name='journeytransition',
            name='to_state',
            field=models.CharField(choices=[('ARRIVED', 'Arrived'), ('IN_REVIEW', 'In review'), ('DIAGNOSED', 'Diagnosed'), ('CLIENT_PAGE', 'Client page'), ('INVITED', 'Invited'), ('NDA_REVIEW', 'NDA review'), ('ASSESSMENT', 'Assessment'), ('POC', 'PoC'), ('INTEGRATION', 'Integration'), ('CUSTOMER_SUCCESS', 'Customer success'), ('DORMANT', 'Dormant'), ('CLIENT', 'Client (deprecated — use NDA_REVIEW)'), ('ENGAGED', 'Engaged (deprecated — use ASSESSMENT/POC/INTEGRATION)')], max_length=20),
        ),
    ]
