# Generated by Django 5.2.15 on 2026-07-21 07:10

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conversations', '0003_initial'),
        ('journey', '0003_migrate_engaged_split'),
    ]

    operations = [
        migrations.CreateModel(
            name='Artifact',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('type', models.CharField(db_index=True, max_length=32)),
                ('version', models.PositiveIntegerField(default=1)),
                ('payload', models.JSONField(blank=True, default=dict)),
                ('disclosure_level', models.CharField(db_index=True, default='public', max_length=24)),
                ('governance_status', models.CharField(choices=[('auto_approved', 'Auto-approved'), ('pending', 'Pending review'), ('approved', 'Approved'), ('blocked', 'Blocked')], db_index=True, default='auto_approved', max_length=16)),
                ('capability_token', models.TextField(blank=True, default='')),
                ('generated_by_run', models.CharField(blank=True, default='', max_length=64)),
                ('pinned', models.BooleanField(default=False)),
                ('superseded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='supersedes', to='journey.artifact')),
                ('thread', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='artifacts', to='conversations.thread')),
            ],
            options={
                'verbose_name': 'Artifact',
                'verbose_name_plural': 'Artifacts',
                'ordering': ['created_at'],
                'indexes': [models.Index(fields=['thread', 'type'], name='journey_art_thread__4a06c0_idx'), models.Index(fields=['type', '-created_at'], name='journey_art_type_f4baf6_idx')],
            },
        ),
        migrations.CreateModel(
            name='CoverageSnapshot',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('dimension', models.CharField(db_index=True, max_length=40)),
                ('status', models.CharField(choices=[('unknown', 'Unknown'), ('partial', 'Partial'), ('covered', 'Covered')], db_index=True, default='unknown', max_length=16)),
                ('evidence_message_id', models.CharField(blank=True, default='', max_length=64)),
                ('thread', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='coverage_snapshots', to='conversations.thread')),
            ],
            options={
                'verbose_name': 'Coverage snapshot',
                'verbose_name_plural': 'Coverage snapshots',
                'constraints': [models.UniqueConstraint(fields=('thread', 'dimension'), name='uniq_coverage_per_thread_dimension')],
            },
        ),
        migrations.CreateModel(
            name='QuestionSuggestion',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('primary_text', models.CharField(max_length=500)),
                ('chips', models.JSONField(blank=True, default=list)),
                ('target_dimension', models.CharField(blank=True, db_index=True, default='', max_length=40)),
                ('agent_run_id', models.CharField(blank=True, default='', max_length=64)),
                ('message', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='question_suggestions', to='conversations.message')),
                ('thread', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='question_suggestions', to='conversations.thread')),
            ],
            options={
                'verbose_name': 'Question suggestion',
                'verbose_name_plural': 'Question suggestions',
                'ordering': ['created_at'],
                'indexes': [models.Index(fields=['thread', 'created_at'], name='journey_que_thread__48a957_idx')],
            },
        ),
    ]
