# Generated by Django 5.0.6 on 2026-06-17 19:27

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='VisitorSession',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('client_id', models.CharField(blank=True, db_index=True, default='', help_text="Stable id generated by the browser; groups a visitor's requests.", max_length=128)),
                ('visitor_type', models.CharField(blank=True, choices=[('problem_owner', 'Problem owner'), ('technical', 'Technical evaluator'), ('research', 'Researcher / scholar'), ('investor', 'Investor'), ('partner', 'Strategic partner'), ('shareholder', 'Shareholder'), ('media', 'Media / journalist'), ('creator', 'Creator'), ('public_infrastructure', 'Public infrastructure'), ('explorer', 'Curious explorer'), ('unknown', 'Unknown')], default='unknown', max_length=32)),
                ('referrer', models.CharField(blank=True, default='', max_length=512)),
                ('user_agent', models.CharField(blank=True, default='', max_length=512)),
                ('ip_hash', models.CharField(blank=True, default='', help_text='Salted hash of the client IP (never the raw address).', max_length=64)),
                ('landing_path', models.CharField(blank=True, default='', max_length=512)),
                ('room_entry_count', models.PositiveIntegerField(default=0)),
                ('last_seen_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Visitor session',
                'verbose_name_plural': 'Visitor sessions',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['client_id', 'created_at'], name='visitors_vi_client__ac4c61_idx')],
            },
        ),
        migrations.CreateModel(
            name='RoomEntry',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('room', models.CharField(choices=[('bottleneck', 'Compute Bottleneck'), ('technical', 'Technical'), ('research', 'Research'), ('investor', 'Investor'), ('partner', 'Partnership'), ('shareholder', 'Shareholder Update'), ('media', 'Media / Journalist'), ('creator', 'Creator / YouTuber'), ('public-infrastructure', 'Public Infrastructure'), ('explore', 'Curious Explorer')], max_length=40)),
                ('visitor_type', models.CharField(blank=True, choices=[('problem_owner', 'Problem owner'), ('technical', 'Technical evaluator'), ('research', 'Researcher / scholar'), ('investor', 'Investor'), ('partner', 'Strategic partner'), ('shareholder', 'Shareholder'), ('media', 'Media / journalist'), ('creator', 'Creator'), ('public_infrastructure', 'Public infrastructure'), ('explorer', 'Curious explorer'), ('unknown', 'Unknown')], default='unknown', max_length=32)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='room_entries', to='visitors.visitorsession')),
            ],
            options={
                'verbose_name': 'Room entry',
                'verbose_name_plural': 'Room entries',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['room', 'created_at'], name='visitors_ro_room_a2b537_idx')],
            },
        ),
    ]
