# Generated by Django 5.0.6 on 2026-06-17 20:44

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("leads", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Evaluation",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("lead_name", models.CharField(blank=True, default="", max_length=255)),
                ("company", models.CharField(blank=True, default="", max_length=255)),
                (
                    "pkg",
                    models.CharField(
                        choices=[
                            (
                                "ALPHA Compute Bottleneck Assessment",
                                "ALPHA Compute Bottleneck Assessment",
                            ),
                            (
                                "ALPHA Core Runtime Fit Assessment",
                                "ALPHA Core Runtime Fit Assessment",
                            ),
                            ("Combined ALPHA Evaluation", "Combined ALPHA Evaluation"),
                        ],
                        default="ALPHA Compute Bottleneck Assessment",
                        max_length=64,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("proposed", "Proposed"),
                            ("in_progress", "In progress"),
                            ("delivered", "Delivered"),
                            ("won", "Won"),
                            ("lost", "Lost"),
                        ],
                        default="proposed",
                        max_length=12,
                    ),
                ),
                ("kpis", models.JSONField(blank=True, default=list)),
                (
                    "lead",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="evaluations",
                        to="leads.lead",
                    ),
                ),
            ],
            options={
                "verbose_name": "Evaluation",
                "verbose_name_plural": "Evaluations",
                "ordering": ["-created_at"],
            },
        ),
    ]
