# Generated by Django 5.2.15 on 2026-07-21 07:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='contract_state',
            field=models.CharField(blank=True, db_index=True, default='', help_text="'' | negotiating | executed | active | churned", max_length=24),
        ),
        migrations.AddField(
            model_name='client',
            name='customer_health',
            field=models.CharField(blank=True, db_index=True, default='', help_text="'' (unknown) | stable | at_risk | critical", max_length=16),
        ),
        migrations.AddField(
            model_name='client',
            name='first_payment_recorded_at',
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
    ]
