# Backend v7.2 Phase 4 — open registration, confirmation, and ONE ADDRESS PER ACCOUNT.
#
# THE CONSTRAINT IS THE POINT OF THIS MIGRATION. `authenticate_client()` resolves a login
# with `filter(email__iexact=...).first()`; with two rows sharing an address, which one you
# signed into was arbitrary. That was latent while accounts were invite-only and becomes
# exploitable the moment anyone can register.
#
# RUN `manage.py audit_client_emails` FIRST. It must come back clean. A migration that fails
# in production because two rows share an address is worse than a command somebody had to
# run, and resolving a duplicate is a human decision — it determines whose conversations,
# attachments and assent record survive.

# Generated by Django 5.2.15 on 2026-07-30 18:43

import django.db.models.deletion
import django.db.models.functions.text
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0002_initial'),
        ('leads', '0005_lead_lead_source'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmailVerificationToken',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('email', models.EmailField(max_length=254)),
                ('token_hash', models.CharField(db_index=True, max_length=64, unique=True)),
                ('expires_at', models.DateTimeField(db_index=True)),
                ('consumed_at', models.DateTimeField(blank=True, null=True)),
                ('invalidated_at', models.DateTimeField(blank=True, null=True)),
                ('requested_ip', models.GenericIPAddressField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Email verification token',
                'verbose_name_plural': 'Email verification tokens',
            },
        ),
        migrations.CreateModel(
            name='PasswordResetToken',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('token_hash', models.CharField(db_index=True, max_length=64, unique=True)),
                ('expires_at', models.DateTimeField(db_index=True)),
                ('consumed_at', models.DateTimeField(blank=True, null=True)),
                ('invalidated_at', models.DateTimeField(blank=True, null=True)),
                ('requested_ip', models.GenericIPAddressField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Password reset token',
                'verbose_name_plural': 'Password reset tokens',
            },
        ),
        migrations.AddField(
            model_name='client',
            name='account_origin',
            field=models.CharField(choices=[('invited', 'Invited'), ('self_serve', 'Self-serve registration')], db_index=True, default='invited', max_length=16),
        ),
        migrations.AddField(
            model_name='client',
            name='email_verified_at',
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name='client',
            name='password_changed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddConstraint(
            model_name='client',
            constraint=models.UniqueConstraint(django.db.models.functions.text.Lower('email'), condition=models.Q(('is_active', True), models.Q(('email', ''), _negated=True)), name='uniq_active_client_email_ci'),
        ),
        migrations.AddField(
            model_name='emailverificationtoken',
            name='client',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='verification_tokens', to='clients.client'),
        ),
        migrations.AddField(
            model_name='passwordresettoken',
            name='client',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reset_tokens', to='clients.client'),
        ),
        migrations.AddIndex(
            model_name='emailverificationtoken',
            index=models.Index(fields=['client', 'consumed_at'], name='clients_ema_client__b1a424_idx'),
        ),
        migrations.AddIndex(
            model_name='passwordresettoken',
            index=models.Index(fields=['client', 'consumed_at'], name='clients_pas_client__34231c_idx'),
        ),
    ]
