# Generated by Django 5.2.15 on 2026-08-10 09:09

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0003_emailverificationtoken_passwordresettoken_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='notification_prefs',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.CreateModel(
            name='ClientTeamInvite',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('email', models.EmailField(db_index=True, max_length=254)),
                ('status', models.CharField(choices=[('invited', 'Invited'), ('revoked', 'Revoked')], db_index=True, default='invited', max_length=16)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='team_invites', to='clients.client')),
            ],
            options={
                'ordering': ['created_at'],
                'constraints': [models.UniqueConstraint(fields=('client', 'email'), name='uniq_invite_per_client_email')],
            },
        ),
    ]
