# Generated by Django 5.2.15 on 2026-08-10 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0004_client_notification_prefs_clientteaminvite'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='nda_requested_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
