# Generated by Django 5.0.6 on 2026-06-17 20:44

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="MetricSnapshot",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "captured_for",
                    models.DateField(
                        db_index=True, help_text="The day this snapshot summarises."
                    ),
                ),
                ("new_leads", models.PositiveIntegerField(default=0)),
                ("tier1_count", models.PositiveIntegerField(default=0)),
                ("tier2_count", models.PositiveIntegerField(default=0)),
                ("overdue_follow_ups", models.PositiveIntegerField(default=0)),
                (
                    "payload",
                    models.JSONField(
                        blank=True, default=dict, help_text="Full overview block JSON."
                    ),
                ),
            ],
            options={
                "verbose_name": "Metric snapshot",
                "verbose_name_plural": "Metric snapshots",
                "ordering": ["-captured_for"],
            },
        ),
        migrations.AddConstraint(
            model_name="metricsnapshot",
            constraint=models.UniqueConstraint(
                fields=("captured_for",), name="unique_snapshot_per_day"
            ),
        ),
    ]
