# Generated by Django 5.0.6 on 2026-06-17 20:09

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GenerationLog',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('product_route', models.CharField(blank=True, default='', max_length=20)),
                ('used_ai', models.BooleanField(default=False)),
                ('chunk_count', models.PositiveIntegerField(default=0)),
                ('prohibited_removed', models.JSONField(blank=True, default=list)),
                ('quant_hedged', models.JSONField(blank=True, default=list)),
                ('ok', models.BooleanField(default=True)),
                ('error', models.TextField(blank=True, default='')),
            ],
            options={
                'verbose_name': 'Generation log',
                'verbose_name_plural': 'Generation logs',
                'ordering': ['-created_at'],
            },
        ),
    ]
