# Generated by Django 5.0.6 on 2026-06-17 19:27

import apps.authentication.models
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('email', models.EmailField(db_index=True, max_length=254, unique=True)),
                ('name', models.CharField(blank=True, max_length=150)),
                ('role', models.CharField(choices=[('ADMIN', 'Admin'), ('ASSESSMENT', 'Assessment'), ('SPECIALIST', 'Specialist'), ('VIEWER', 'Viewer')], default='VIEWER', help_text='Permission role (drives access control).', max_length=20)),
                ('team_role', models.CharField(choices=[('Admin', 'Admin'), ('Assessment Team', 'Assessment Team'), ('Technical Review Team', 'Technical Review Team'), ('Expert Concierge', 'Expert Concierge'), ('Success Team', 'Success Team'), ('Specialist', 'Specialist'), ('Media Contact', 'Media Contact')], default='Assessment Team', help_text='Display label shown to the team in the dashboard.', max_length=40)),
                ('avatar_url', models.URLField(blank=True, default='')),
                ('is_active', models.BooleanField(default=True)),
                ('is_staff', models.BooleanField(default=False, help_text='Can access the Django admin.')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'Team member',
                'verbose_name_plural': 'Team members',
                'ordering': ['name', 'email'],
            },
            managers=[
                ('objects', apps.authentication.models.UserManager()),
            ],
        ),
    ]
