# Generated by Django 5.0.6 on 2026-06-17 20:44

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("leads", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="EmailLog",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "kind",
                    models.CharField(
                        choices=[
                            ("confirmation", "Visitor confirmation"),
                            ("internal_alert", "Internal alert"),
                            ("follow_up", "Follow-up"),
                            ("visitor", "Visitor (generic)"),
                        ],
                        max_length=20,
                    ),
                ),
                ("to_email", models.EmailField(max_length=254)),
                (
                    "from_email",
                    models.EmailField(blank=True, default="", max_length=254),
                ),
                ("subject", models.CharField(max_length=512)),
                ("body", models.TextField(blank=True, default="")),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("stubbed", "Stubbed (delivery disabled)"),
                            ("sent", "Sent"),
                            ("failed", "Failed"),
                        ],
                        default="stubbed",
                        max_length=12,
                    ),
                ),
                ("error", models.TextField(blank=True, default="")),
                (
                    "provider_message_id",
                    models.CharField(blank=True, default="", max_length=255),
                ),
                (
                    "lead",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="emails",
                        to="leads.lead",
                    ),
                ),
            ],
            options={
                "verbose_name": "Email log",
                "verbose_name_plural": "Email logs",
                "ordering": ["-created_at"],
            },
        ),
    ]
