# Generated by Django 5.2.14 on 2026-06-19 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emails', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='emaillog',
            name='attachments',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='emaillog',
            name='cc',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='emaillog',
            name='scheduled_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
