# Generated by Django 5.0.6 on 2026-07-01 20:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emails', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emaillog',
            name='kind',
            field=models.CharField(choices=[('confirmation', 'Visitor confirmation'), ('internal_alert', 'Internal alert'), ('follow_up', 'Follow-up'), ('visitor', 'Visitor (generic)'), ('client_page_reveal', 'Client page reveal'), ('account_invite', 'Account invite')], max_length=20),
        ),
    ]
