# Generated by Django 5.0.6 on 2026-07-07 17:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('emails', '0002_alter_emaillog_kind'),
        ('emails', '0002_emaillog_attachments_emaillog_cc_and_more'),
    ]

    operations = [
    ]
