# Backend v7.2 Phase 4 — the three TRANSACTIONAL email kinds.
#
# `email_verification`, `password_reset` and `address_in_use` are the only kinds permitted to
# reach an UNCONFIRMED address, because confirming it is what they are for. The gate lives in
# `email_sender.send_email`, the single choke-point for outbound mail (R66).
#
# The values are short on purpose: `kind` is max_length=20, and "signup_address_in_use" would
# not fit.

# Generated by Django 5.2.15 on 2026-07-30 18:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emails', '0003_merge_20260707_2009'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emaillog',
            name='kind',
            field=models.CharField(choices=[('confirmation', 'Visitor confirmation'), ('internal_alert', 'Internal alert'), ('follow_up', 'Follow-up'), ('visitor', 'Visitor (generic)'), ('client_page_reveal', 'Client page reveal'), ('account_invite', 'Account invite'), ('password_reset', 'Password reset'), ('email_verification', 'Email verification'), ('address_in_use', 'Address already in use')], max_length=20),
        ),
    ]
