# Generated by Django 5.2.14 on 2026-06-19 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('follow_up', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='followuptask',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('completed', 'Completed'), ('snoozed', 'Snoozed'), ('dismissed', 'Dismissed')], db_index=True, default='pending', max_length=12),
        ),
    ]
