# Generated by Django 5.2.15 on 2026-07-21 06:03

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Persona',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('persona_id', models.CharField(db_index=True, max_length=16, unique=True)),
                ('company', models.CharField(db_index=True, max_length=120)),
                ('department', models.CharField(blank=True, default='', max_length=200)),
                ('primary_persona', models.CharField(blank=True, default='', max_length=200)),
                ('functional_family', models.CharField(choices=[('ai_model_systems', 'AI & Model Systems'), ('cloud_infrastructure', 'Cloud & Infrastructure'), ('silicon_memory_hardware', 'Silicon, Memory & Hardware'), ('runtime_hpc_simulation', 'Runtime, HPC & Simulation'), ('strategic_product_partnerships', 'Strategic Product & Partnerships')], db_index=True, max_length=40)),
                ('pitch_archetype', models.CharField(blank=True, default='', max_length=120)),
                ('buying_role', models.CharField(blank=True, default='', max_length=200)),
                ('decision_lens', models.CharField(blank=True, default='', max_length=300)),
                ('department_mandate', models.TextField(blank=True, default='')),
                ('trigger_event', models.TextField(blank=True, default='')),
                ('primary_kpi', models.CharField(blank=True, default='', max_length=200)),
                ('supporting_kpis', models.JSONField(blank=True, default=list)),
                ('workload_environment', models.TextField(blank=True, default='')),
                ('boundary_waste_hypothesis', models.TextField(blank=True, default='')),
                ('desired_gain', models.TextField(blank=True, default='')),
                ('likely_champion', models.CharField(blank=True, default='', max_length=200)),
                ('likely_blocker', models.CharField(blank=True, default='', max_length=200)),
                ('likely_objection', models.TextField(blank=True, default='')),
                ('response_angle', models.TextField(blank=True, default='')),
                ('first_value_artifact', models.CharField(blank=True, default='', max_length=200)),
                ('personalized_cta', models.CharField(blank=True, default='', max_length=200)),
                ('commercial_route', models.CharField(blank=True, default='', max_length=200)),
                ('product_route', models.CharField(blank=True, default='', max_length=200)),
                ('disclosure_ceiling', models.CharField(choices=[('public', 'Public'), ('controlled_public', 'Controlled public'), ('nda_only', 'NDA only')], default='controlled_public', max_length=24)),
                ('priority', models.PositiveSmallIntegerField(default=3)),
                ('validation_status', models.CharField(choices=[('hypothesis', 'Hypothesis'), ('validated', 'Validated'), ('rejected', 'Rejected')], default='hypothesis', max_length=16)),
                ('department_confidence', models.TextField(blank=True, default='')),
            ],
            options={
                'verbose_name': 'Persona',
                'verbose_name_plural': 'Personas',
                'ordering': ['persona_id'],
                'indexes': [models.Index(fields=['functional_family', 'priority'], name='personas_pe_functio_001ecf_idx'), models.Index(fields=['company', 'functional_family'], name='personas_pe_company_655138_idx')],
            },
        ),
        migrations.CreateModel(
            name='PitchRoom',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('pitch_room_id', models.CharField(db_index=True, max_length=24, unique=True)),
                ('title', models.CharField(blank=True, default='', max_length=300)),
                ('slides', models.JSONField(blank=True, default=list)),
                ('review_status', models.CharField(blank=True, default='draft', max_length=40)),
                ('persona', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='pitch_room', to='personas.persona')),
            ],
            options={
                'verbose_name': 'Pitch room',
                'verbose_name_plural': 'Pitch rooms',
                'ordering': ['pitch_room_id'],
            },
        ),
    ]
