# Generated by Django 5.2.15 on 2026-07-21 06:03

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0001_initial'),
        ('conversations', '0001_initial'),
        ('leads', '0003_merge_20260707_2009'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='context_note',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='message',
            name='seq',
            field=models.PositiveIntegerField(db_index=True, default=0),
        ),
        migrations.AddField(
            model_name='message',
            name='streaming_status',
            field=models.CharField(choices=[('pending', 'Pending'), ('streaming', 'Streaming'), ('settled', 'Settled'), ('halted', 'Halted'), ('under_review', 'Under review')], db_index=True, default='settled', max_length=16),
        ),
        migrations.AddField(
            model_name='message',
            name='summary_of',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='conversation',
            name='context',
            field=models.CharField(choices=[('review', 'Review (anonymous)'), ('anonymous_review', 'Anonymous review (public plane)'), ('client_page', 'Client page'), ('portal', 'Portal (client)'), ('customer_success', 'Customer success'), ('console', 'Team console')], db_index=True, max_length=16),
        ),
        migrations.CreateModel(
            name='Thread',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('owner_kind', models.CharField(choices=[('session', 'Visitor session (anonymous)'), ('client', 'Client'), ('team', 'Team')], db_index=True, default='session', max_length=16)),
                ('visitor_session', models.CharField(blank=True, db_index=True, default='', max_length=64)),
                ('context', models.CharField(choices=[('review', 'Review'), ('anonymous_review', 'Anonymous review'), ('client_page', 'Client page'), ('portal', 'Portal'), ('customer_success', 'Customer success')], db_index=True, default='anonymous_review', max_length=24)),
                ('title', models.CharField(blank=True, default='', max_length=200)),
                ('title_source', models.CharField(choices=[('generated', 'Generated'), ('user', 'User')], default='generated', max_length=16)),
                ('state_at_creation', models.CharField(blank=True, default='ARRIVED', max_length=20)),
                ('last_activity_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('claimed_at', models.DateTimeField(blank=True, null=True)),
                ('retention_expires_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('client', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='threads', to='clients.client')),
                ('conversation', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='thread', to='conversations.conversation')),
                ('lead', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='threads', to='leads.lead')),
            ],
            options={
                'verbose_name': 'Thread',
                'verbose_name_plural': 'Threads',
                'ordering': ['-last_activity_at', '-created_at'],
            },
        ),
        migrations.AddField(
            model_name='message',
            name='thread',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='conversations.thread'),
        ),
        migrations.CreateModel(
            name='ThreadParticipant',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('principal_kind', models.CharField(choices=[('session', 'Visitor session'), ('client', 'Client'), ('user', 'Team user'), ('agent', 'Agent')], max_length=16)),
                ('principal_id', models.CharField(max_length=128)),
                ('role', models.CharField(choices=[('visitor', 'Visitor'), ('agent', 'Agent'), ('team', 'Team')], default='visitor', max_length=16)),
                ('joined_at', models.DateTimeField(auto_now_add=True)),
                ('thread', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='participants', to='conversations.thread')),
            ],
            options={
                'verbose_name': 'Thread participant',
                'verbose_name_plural': 'Thread participants',
            },
        ),
        migrations.AddIndex(
            model_name='thread',
            index=models.Index(fields=['visitor_session', '-last_activity_at'], name='conversatio_visitor_e60c37_idx'),
        ),
        migrations.AddIndex(
            model_name='thread',
            index=models.Index(fields=['client', '-last_activity_at'], name='conversatio_client__ce0bb3_idx'),
        ),
        migrations.AddIndex(
            model_name='thread',
            index=models.Index(fields=['owner_kind', 'context'], name='conversatio_owner_k_acacd6_idx'),
        ),
        migrations.AddIndex(
            model_name='thread',
            index=models.Index(fields=['retention_expires_at'], name='conversatio_retenti_495964_idx'),
        ),
        migrations.AddIndex(
            model_name='threadparticipant',
            index=models.Index(fields=['thread', 'role'], name='conversatio_thread__7ae4e4_idx'),
        ),
        migrations.AddConstraint(
            model_name='threadparticipant',
            constraint=models.UniqueConstraint(fields=('thread', 'principal_kind', 'principal_id'), name='uniq_thread_participant'),
        ),
    ]
