# Generated by Django 5.2.15 on 2026-07-21 07:10

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conversations', '0002_thread_spine'),
    ]

    operations = [
        migrations.CreateModel(
            name='MessageAttachment',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('attachment_id', models.CharField(db_index=True, max_length=64)),
                ('order', models.PositiveSmallIntegerField(default=0)),
                ('message', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachment_links', to='conversations.message')),
            ],
            options={
                'verbose_name': 'Message attachment',
                'verbose_name_plural': 'Message attachments',
                'ordering': ['order', 'created_at'],
                'constraints': [models.UniqueConstraint(fields=('message', 'attachment_id'), name='uniq_attachment_per_message')],
            },
        ),
    ]
