# Generated by Django 5.2.15 on 2026-07-31 18:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conversations', '0003_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='thread',
            name='current_state',
            field=models.CharField(blank=True, db_index=True, default='ARRIVED', max_length=20),
        ),
        migrations.AddField(
            model_name='thread',
            name='questions_asked',
            field=models.PositiveSmallIntegerField(default=0),
        ),
    ]
